"""Registry compile constants and output naming contract."""

REGISTRY_FORMAT_VERSION = "1.0.0"
COMPILER_VERSION = "1.18.0"
DEFAULT_BUNDLE_ID = "bundle.base.lab"
DEFAULT_REGISTRY_OUT_DIR_REL = "build/registries"
DEFAULT_LOCKFILE_OUT_REL = "build/lockfile.json"
DEFAULT_COMPATIBILITY_VERSION = "1.0.0"


REGISTRY_OUTPUT_FILENAMES = {
    "time_control_policy_registry": "time_control_policy.registry.json",
    "dt_quantization_rule_registry": "dt_quantization_rule.registry.json",
    "compaction_policy_registry": "compaction_policy.registry.json",
    "conservation_contract_set_registry": "conservation_contract_set.registry.json",
    "quantity_registry": "quantity.registry.json",
    "exception_type_registry": "exception_type.registry.json",
    "universe_physics_profile_registry": "universe_physics_profile.registry.json",
    "time_model_registry": "time_model.registry.json",
    "numeric_precision_policy_registry": "numeric_precision_policy.registry.json",
    "tier_taxonomy_registry": "tier_taxonomy.registry.json",
    "transition_policy_registry": "transition_policy.registry.json",
    "arbitration_rule_registry": "arbitration_rule.registry.json",
    "budget_envelope_registry": "budget_envelope.registry.json",
    "arbitration_policy_registry": "arbitration_policy.registry.json",
    "inspection_cache_policy_registry": "inspection_cache_policy.registry.json",
    "boundary_model_registry": "boundary_model.registry.json",
    "domain_registry": "domain.registry.json",
    "law_registry": "law.registry.json",
    "experience_registry": "experience.registry.json",
    "lens_registry": "lens.registry.json",
    "net_replication_policy_registry": "net_replication_policy.registry.json",
    "net_resync_strategy_registry": "net_resync_strategy.registry.json",
    "net_server_policy_registry": "net_server_policy.registry.json",
    "securex_policy_registry": "securex_policy.registry.json",
    "server_profile_registry": "server_profile.registry.json",
    "shard_map_registry": "shard_map.registry.json",
    "perception_interest_policy_registry": "perception_interest_policy.registry.json",
    "control_action_registry": "control_action.registry.json",
    "interaction_action_registry": "interaction_action.registry.json",
    "controller_type_registry": "controller_type.registry.json",
    "governance_type_registry": "governance_type.registry.json",
    "diplomatic_state_registry": "diplomatic_state.registry.json",
    "cohort_mapping_policy_registry": "cohort_mapping_policy.registry.json",
    "order_type_registry": "order_type.registry.json",
    "role_registry": "role.registry.json",
    "institution_type_registry": "institution_type.registry.json",
    "commitment_type_registry": "commitment_type.registry.json",
    "causality_strictness_registry": "causality_strictness.registry.json",
    "demography_policy_registry": "demography_policy.registry.json",
    "death_model_registry": "death_model.registry.json",
    "birth_model_registry": "birth_model.registry.json",
    "migration_model_registry": "migration_model.registry.json",
    "body_shape_registry": "body_shape.registry.json",
    "view_mode_registry": "view_mode.registry.json",
    "instrument_type_registry": "instrument_type.registry.json",
    "calibration_model_registry": "calibration_model.registry.json",
    "render_proxy_registry": "render_proxy.registry.json",
    "cosmetic_registry": "cosmetic.registry.json",
    "cosmetic_policy_registry": "cosmetic_policy.registry.json",
    "render_primitive_registry": "render_primitive.registry.json",
    "procedural_material_template_registry": "procedural_material_template.registry.json",
    "label_policy_registry": "label_policy.registry.json",
    "lod_policy_registry": "lod_policy.registry.json",
    "representation_rule_registry": "representation_rule.registry.json",
    "epistemic_policy_registry": "epistemic_policy.registry.json",
    "retention_policy_registry": "retention_policy.registry.json",
    "decay_model_registry": "decay_model.registry.json",
    "eviction_rule_registry": "eviction_rule.registry.json",
    "anti_cheat_policy_registry": "anti_cheat_policy.registry.json",
    "anti_cheat_module_registry": "anti_cheat_module.registry.json",
    "activation_policy_registry": "activation_policy.registry.json",
    "budget_policy_registry": "budget_policy.registry.json",
    "fidelity_policy_registry": "fidelity_policy.registry.json",
    "worldgen_constraints_registry": "worldgen_constraints.registry.json",
    "astronomy_catalog_index": "astronomy.catalog.index.json",
    "site_registry_index": "site.registry.index.json",
    "ephemeris_registry": "ephemeris.registry.json",
    "terrain_tile_registry": "terrain.tile.registry.json",
    "ui_registry": "ui.registry.json",
}
