"""Deterministic embodiment helpers for EMB-0."""

from .body import (
    DEFAULT_BODY_TEMPLATE_ID,
    body_state_rows_by_subject_id,
    body_template_registry_hash,
    body_template_rows_by_id,
    build_body_state,
    instantiate_body_system,
    normalize_body_state_rows,
)
from .collision import (
    DEFAULT_COLLISION_PROVIDER_ID,
    DEFAULT_MOVEMENT_SLOPE_PARAMS_ID,
    collision_provider_rows_by_id,
    invalidate_macro_heightfield_cache_for_tiles,
    movement_slope_params_rows_by_id,
    resolve_macro_heightfield_sample,
)
from .lens import (
    lens_profile_registry_hash,
    lens_profile_rows_by_id,
    resolve_authorized_lens_profile,
    resolve_lens_camera_state,
)
from .tools import (
    access_policy_registry_hash,
    access_policy_rows_by_id,
    build_cut_trench_task,
    build_fill_at_cursor_task,
    build_logic_probe_task,
    build_logic_trace_task,
    build_mine_at_cursor_task,
    build_scan_result,
    build_teleport_tool_surface,
    build_tool_surface_row,
    build_toolbelt_availability_surface,
    entitlement_registry_hash,
    entitlement_rows_by_id,
    evaluate_tool_access,
    tool_capability_registry_hash,
    tool_capability_rows_by_id,
)

__all__ = [
    "DEFAULT_BODY_TEMPLATE_ID",
    "DEFAULT_COLLISION_PROVIDER_ID",
    "DEFAULT_MOVEMENT_SLOPE_PARAMS_ID",
    "body_state_rows_by_subject_id",
    "body_template_registry_hash",
    "body_template_rows_by_id",
    "build_body_state",
    "collision_provider_rows_by_id",
    "invalidate_macro_heightfield_cache_for_tiles",
    "instantiate_body_system",
    "movement_slope_params_rows_by_id",
    "normalize_body_state_rows",
    "access_policy_registry_hash",
    "access_policy_rows_by_id",
    "build_cut_trench_task",
    "build_fill_at_cursor_task",
    "build_logic_probe_task",
    "build_logic_trace_task",
    "build_mine_at_cursor_task",
    "build_scan_result",
    "build_teleport_tool_surface",
    "build_tool_surface_row",
    "build_toolbelt_availability_surface",
    "entitlement_registry_hash",
    "entitlement_rows_by_id",
    "evaluate_tool_access",
    "lens_profile_registry_hash",
    "lens_profile_rows_by_id",
    "resolve_authorized_lens_profile",
    "resolve_lens_camera_state",
    "resolve_macro_heightfield_sample",
    "tool_capability_registry_hash",
    "tool_capability_rows_by_id",
]
