"""SYS domain exports."""

from src.system.system_collapse_engine import (
    REFUSAL_SYSTEM_COLLAPSE_INELIGIBLE,
    REFUSAL_SYSTEM_COLLAPSE_INVALID,
    SystemCollapseError,
    boundary_invariant_rows_by_id,
    build_boundary_invariant_row,
    build_interface_signature_row,
    build_system_macro_capsule_row,
    build_system_state_vector_row,
    collapse_system_graph,
    interface_signature_rows_by_system,
    normalize_boundary_invariant_rows,
    normalize_interface_signature_rows,
    normalize_system_macro_capsule_rows,
    normalize_system_rows,
    normalize_system_state_vector_rows,
    system_rows_by_id,
)
from src.system.system_expand_engine import (
    REFUSAL_SYSTEM_EXPAND_HASH_MISMATCH,
    REFUSAL_SYSTEM_EXPAND_INVALID,
    SystemExpandError,
    expand_system_graph,
)
from src.system.system_validation_engine import (
    REFUSAL_SYSTEM_INVALID_INTERFACE,
    REFUSAL_SYSTEM_INVALID_MACRO_MODEL_SET,
    REFUSAL_SYSTEM_INVARIANT_VIOLATION,
    validate_boundary_invariants,
    validate_interface_signature,
    validate_macro_model_set,
)

__all__ = [
    "REFUSAL_SYSTEM_COLLAPSE_INELIGIBLE",
    "REFUSAL_SYSTEM_COLLAPSE_INVALID",
    "SystemCollapseError",
    "build_interface_signature_row",
    "normalize_interface_signature_rows",
    "interface_signature_rows_by_system",
    "build_boundary_invariant_row",
    "normalize_boundary_invariant_rows",
    "boundary_invariant_rows_by_id",
    "build_system_state_vector_row",
    "normalize_system_state_vector_rows",
    "build_system_macro_capsule_row",
    "normalize_system_macro_capsule_rows",
    "normalize_system_rows",
    "system_rows_by_id",
    "collapse_system_graph",
    "REFUSAL_SYSTEM_EXPAND_INVALID",
    "REFUSAL_SYSTEM_EXPAND_HASH_MISMATCH",
    "SystemExpandError",
    "expand_system_graph",
    "REFUSAL_SYSTEM_INVALID_INTERFACE",
    "REFUSAL_SYSTEM_INVARIANT_VIOLATION",
    "REFUSAL_SYSTEM_INVALID_MACRO_MODEL_SET",
    "validate_interface_signature",
    "validate_boundary_invariants",
    "validate_macro_model_set",
]
