"""Deterministic session stage/abort/resume controls for pipeline discipline."""

from __future__ import annotations

import os
from typing import Dict, List, Tuple

from tools.xstack.compatx.canonical_json import canonical_sha256
from tools.xstack.compatx.validator import validate_instance
from tools.xstack.registry_compile.constants import DEFAULT_BUNDLE_ID
from tools.xstack.registry_compile.lockfile import validate_lockfile_payload

from .common import norm, now_utc_iso, read_json_object, refusal, write_canonical_json
from .pipeline_contract import DEFAULT_PIPELINE_ID, load_session_pipeline_contract
from .runner import _latest_run_meta, _load_lockfile, _load_schema_validated, _validate_registry_hashes, boot_session_spec


def _authority_compatible(previous: dict, current: dict) -> int:
    if not isinstance(previous, dict) or not isinstance(current, dict):
        return 0
    if str(previous.get("authority_origin", "")).strip() != str(current.get("authority_origin", "")).strip():
        return 0
    if str(previous.get("experience_id", "")).strip() != str(current.get("experience_id", "")).strip():
        return 0
    if str(previous.get("law_profile_id", "")).strip() != str(current.get("law_profile_id", "")).strip():
        return 0
    if str(previous.get("privilege_level", "")).strip() != str(current.get("privilege_level", "")).strip():
        return 0
    previous_entitlements = sorted(set(str(item).strip() for item in (previous.get("entitlements") or []) if str(item).strip()))
    current_entitlements = sorted(set(str(item).strip() for item in (current.get("entitlements") or []) if str(item).strip()))
    return 1 if previous_entitlements == current_entitlements else 0


def _load_session_spec(repo_root: str, session_spec_path: str) -> Tuple[dict, Dict[str, object], str]:
    spec_abs = os.path.normpath(os.path.abspath(session_spec_path))
    session_spec, spec_error = _load_schema_validated(repo_root=repo_root, schema_name="session_spec", path=spec_abs)
    if spec_error:
        return {}, spec_error, ""
    return session_spec, {}, spec_abs


def _save_paths(repo_root: str, session_spec: dict) -> Tuple[str, str, str]:
    save_id = str(session_spec.get("save_id", "")).strip()
    save_dir = os.path.join(repo_root, "saves", save_id)
    identity_path = os.path.join(save_dir, "universe_identity.json")
    return save_id, save_dir, identity_path


def _normalized_stage_log(rows: object) -> List[dict]:
    out: List[dict] = []
    if not isinstance(rows, list):
        return out
    for row in rows:
        if not isinstance(row, dict):
            continue
        out.append(
            {
                "stage_index": int(row.get("stage_index", 0) or 0),
                "command_id": str(row.get("command_id", "")),
                "from_stage_id": str(row.get("from_stage_id", "")),
                "to_stage_id": str(row.get("to_stage_id", "")),
                "status": str(row.get("status", "")),
                "reason_code": str(row.get("reason_code", "")),
                "observer_watermark": str(row.get("observer_watermark", "")),
            }
        )
    return sorted(
        out,
        key=lambda item: (
            int(item.get("stage_index", 0) or 0),
            str(item.get("command_id", "")),
            str(item.get("to_stage_id", "")),
        ),
    )


def session_stage_status(
    repo_root: str,
    session_spec_path: str,
) -> Dict[str, object]:
    session_spec, spec_error, spec_abs = _load_session_spec(repo_root=repo_root, session_spec_path=session_spec_path)
    if spec_error:
        return spec_error

    pipeline_contract = load_session_pipeline_contract(
        repo_root=repo_root,
        pipeline_id=str(session_spec.get("pipeline_id", "")),
    )
    if pipeline_contract.get("result") != "complete":
        return pipeline_contract

    stage_map = dict(pipeline_contract.get("stage_map") or {})
    pipeline = dict(pipeline_contract.get("pipeline") or {})
    save_id, save_dir, _identity_path = _save_paths(repo_root=repo_root, session_spec=session_spec)
    previous_run_meta, previous_path = _latest_run_meta(save_dir)
    stage_id = str(previous_run_meta.get("last_stage_id", "")).strip() if isinstance(previous_run_meta, dict) else ""
    if not stage_id:
        stage_id = str(pipeline.get("entry_stage_id", "stage.resolve_session"))
    if stage_id not in stage_map:
        return refusal(
            "refusal.stage_invalid_transition",
            "run-meta stage '{}' is not declared in session pipeline".format(stage_id),
            "Use a save generated by the active session pipeline contracts.",
            {"stage_id": stage_id},
            "$.last_stage_id",
        )

    stage_desc = dict(stage_map.get(stage_id) or {})
    stage_log = _normalized_stage_log((previous_run_meta or {}).get("stage_log"))
    refusal_codes = sorted(
        set(str(row.get("reason_code", "")).strip() for row in stage_log if str(row.get("reason_code", "")).strip())
    )
    return {
        "result": "complete",
        "save_id": save_id,
        "pipeline_id": str(pipeline_contract.get("pipeline_id", DEFAULT_PIPELINE_ID)),
        "session_spec_path": norm(os.path.relpath(spec_abs, repo_root)),
        "current_stage_id": stage_id,
        "abort_allowed": bool(stage_desc.get("abort_allowed", False)),
        "resume_allowed": bool(stage_desc.get("resume_allowed", False)),
        "deterministic": bool(stage_desc.get("deterministic", False)),
        "last_run_meta_path": norm(os.path.relpath(previous_path, repo_root)) if previous_path else "",
        "stage_log": stage_log,
        "refusal_codes": refusal_codes,
    }


def abort_session_spec(
    repo_root: str,
    session_spec_path: str,
    stage_id: str = "",
    reason: str = "manual_abort",
) -> Dict[str, object]:
    session_spec, spec_error, spec_abs = _load_session_spec(repo_root=repo_root, session_spec_path=session_spec_path)
    if spec_error:
        return spec_error

    pipeline_contract = load_session_pipeline_contract(
        repo_root=repo_root,
        pipeline_id=str(session_spec.get("pipeline_id", "")),
    )
    if pipeline_contract.get("result") != "complete":
        return pipeline_contract
    stage_map = dict(pipeline_contract.get("stage_map") or {})
    pipeline = dict(pipeline_contract.get("pipeline") or {})
    stage_token = str(stage_id).strip()
    save_id, save_dir, identity_path = _save_paths(repo_root=repo_root, session_spec=session_spec)
    previous_run_meta, previous_path = _latest_run_meta(save_dir)
    if not stage_token:
        stage_token = str(previous_run_meta.get("last_stage_id", "")).strip() if isinstance(previous_run_meta, dict) else ""
    if not stage_token:
        stage_token = str(pipeline.get("ready_stage_id", "stage.session_ready"))

    stage_desc = dict(stage_map.get(stage_token) or {})
    if not stage_desc:
        return refusal(
            "refusal.stage_invalid_transition",
            "cannot abort from unknown stage '{}'".format(stage_token),
            "Abort from a declared stage_id in the session stage registry.",
            {"stage_id": stage_token},
            "$.stage_id",
        )
    if not bool(stage_desc.get("abort_allowed", False)):
        return refusal(
            "refusal.stage_invalid_transition",
            "abort is not allowed from stage '{}'".format(stage_token),
            "Abort only from stages with abort_allowed=true.",
            {"stage_id": stage_token},
            "$.stage_id",
        )

    bundle_token = str(session_spec.get("bundle_id", "")).strip() or DEFAULT_BUNDLE_ID
    lock_payload, lock_error = _load_lockfile(
        repo_root=repo_root,
        compile_if_missing=False,
        bundle_id=bundle_token,
        lockfile_path="",
    )
    if lock_error:
        return lock_error
    lock_semantic = validate_lockfile_payload(lock_payload)
    if lock_semantic.get("result") != "complete":
        return refusal(
            "refusal.resume_hash_mismatch",
            "lockfile failed deterministic hash validation during abort snapshot",
            "Rebuild lockfile and retry.",
            {"bundle_id": bundle_token},
            "$.pack_lock_hash",
        )

    identity_payload, identity_error = _load_schema_validated(repo_root=repo_root, schema_name="universe_identity", path=identity_path)
    if identity_error:
        return identity_error

    run_meta = {
        "schema_version": "1.0.0",
        "run_kind": "abort",
        "save_id": save_id,
        "bundle_id": bundle_token,
        "pipeline_id": str(pipeline_contract.get("pipeline_id", DEFAULT_PIPELINE_ID)),
        "session_spec_path": norm(os.path.relpath(spec_abs, repo_root)),
        "pack_lock_hash": str(lock_payload.get("pack_lock_hash", "")),
        "registry_hashes": dict((lock_payload.get("registries") or {})),
        "authority_context": dict(session_spec.get("authority_context") or {}),
        "universe_identity_hash": str(identity_payload.get("identity_hash", "")),
        "last_stage_id": stage_token,
        "aborted": True,
        "abort_reason": str(reason).strip() or "manual_abort",
        "stage_log": [
            {
                "stage_index": 0,
                "command_id": "client.session.abort",
                "from_stage_id": stage_token,
                "to_stage_id": "stage.teardown_session",
                "status": "pass",
                "reason_code": "",
                "observer_watermark": "OBSERVER MODE" if str((session_spec.get("authority_context") or {}).get("privilege_level", "")).strip() == "observer" else "",
            }
        ],
        "source_run_meta_path": norm(os.path.relpath(previous_path, repo_root)) if previous_path else "",
        "started_utc": now_utc_iso(),
        "stopped_utc": now_utc_iso(),
    }
    run_meta_hash = canonical_sha256(run_meta)
    run_id = "run.abort.{}".format(run_meta_hash[:16])
    run_meta["run_id"] = run_id
    run_meta["deterministic_fields_hash"] = run_meta_hash

    run_meta_dir = os.path.join(save_dir, "run_meta")
    run_meta_path = os.path.join(run_meta_dir, "{}.json".format(run_id))
    write_canonical_json(run_meta_path, run_meta)
    return {
        "result": "complete",
        "run_id": run_id,
        "save_id": save_id,
        "last_stage_id": stage_token,
        "run_meta_path": norm(os.path.relpath(run_meta_path, repo_root)),
    }


def resume_session_spec(
    repo_root: str,
    session_spec_path: str,
    bundle_id: str = "",
    lockfile_path: str = "",
    registries_dir: str = "",
) -> Dict[str, object]:
    session_spec, spec_error, spec_abs = _load_session_spec(repo_root=repo_root, session_spec_path=session_spec_path)
    if spec_error:
        return spec_error
    pipeline_contract = load_session_pipeline_contract(
        repo_root=repo_root,
        pipeline_id=str(session_spec.get("pipeline_id", "")),
    )
    if pipeline_contract.get("result") != "complete":
        return pipeline_contract

    save_id, save_dir, identity_path = _save_paths(repo_root=repo_root, session_spec=session_spec)
    previous_run_meta, previous_path = _latest_run_meta(save_dir)
    if not previous_path or not isinstance(previous_run_meta, dict):
        return refusal(
            "refusal.resume_incompatible",
            "resume requested but no previous run_meta snapshot exists",
            "Boot a session first or create an abort/suspend snapshot before resuming.",
            {"save_id": save_id},
            "$.run_meta",
        )

    previous_last_stage_id = str(previous_run_meta.get("last_stage_id", "")).strip()
    stage_desc = dict((pipeline_contract.get("stage_map") or {}).get(previous_last_stage_id) or {})
    if not stage_desc or not bool(stage_desc.get("resume_allowed", False)):
        return refusal(
            "refusal.resume_incompatible",
            "resume is not allowed from stage '{}'".format(previous_last_stage_id or "<empty>"),
            "Resume only from stages with resume_allowed=true.",
            {"last_stage_id": previous_last_stage_id or "<empty>"},
            "$.last_stage_id",
        )

    bundle_token = str(bundle_id).strip() or str(session_spec.get("bundle_id", "")).strip() or DEFAULT_BUNDLE_ID
    lock_payload, lock_error = _load_lockfile(
        repo_root=repo_root,
        compile_if_missing=False,
        bundle_id=bundle_token,
        lockfile_path=lockfile_path,
    )
    if lock_error:
        return lock_error
    lock_semantic = validate_lockfile_payload(lock_payload)
    if lock_semantic.get("result") != "complete":
        return refusal(
            "refusal.resume_hash_mismatch",
            "lockfile failed deterministic hash validation during resume",
            "Rebuild lockfile and retry resume.",
            {"bundle_id": bundle_token},
            "$.pack_lock_hash",
        )

    registry_check = _validate_registry_hashes(
        repo_root=repo_root,
        lockfile_payload=lock_payload,
        compile_if_missing=False,
        bundle_id=bundle_token,
        registries_dir=registries_dir,
    )
    if registry_check.get("result") != "complete":
        return registry_check

    if str(previous_run_meta.get("pack_lock_hash", "")).strip() != str(lock_payload.get("pack_lock_hash", "")).strip():
        return refusal(
            "refusal.resume_hash_mismatch",
            "pack_lock_hash mismatch detected during resume",
            "Use a compatible dist/lockfile for this save.",
            {
                "save_id": save_id,
            },
            "$.pack_lock_hash",
        )
    if dict(previous_run_meta.get("registry_hashes") or {}) != dict(lock_payload.get("registries") or {}):
        return refusal(
            "refusal.resume_hash_mismatch",
            "registry hash mismatch detected during resume",
            "Use registries compiled from the same lockfile as the save snapshot.",
            {
                "save_id": save_id,
            },
            "$.registry_hashes",
        )

    identity_payload, identity_error = _load_schema_validated(repo_root=repo_root, schema_name="universe_identity", path=identity_path)
    if identity_error:
        return identity_error
    previous_identity_hash = str(previous_run_meta.get("universe_identity_hash", "")).strip()
    if previous_identity_hash and previous_identity_hash != str(identity_payload.get("identity_hash", "")).strip():
        return refusal(
            "refusal.resume_identity_violation",
            "UniverseIdentity hash mismatch detected during resume",
            "Restore original universe_identity.json for this save before resume.",
            {"save_id": save_id},
            "$.universe_identity",
        )

    previous_authority = dict(previous_run_meta.get("authority_context") or {})
    current_authority = dict(session_spec.get("authority_context") or {})
    if not _authority_compatible(previous_authority, current_authority):
        return refusal(
            "refusal.resume_incompatible",
            "authority context is incompatible with resume snapshot",
            "Resume using the same authority origin/profile/entitlements as the snapshot.",
            {"save_id": save_id},
            "$.authority_context",
        )

    resumed = boot_session_spec(
        repo_root=repo_root,
        session_spec_path=spec_abs,
        bundle_id=bundle_token,
        compile_if_missing=False,
        lockfile_path=lockfile_path,
        registries_dir=registries_dir,
    )
    if resumed.get("result") != "complete":
        return resumed
    resumed["resume_source_run_id"] = str(previous_run_meta.get("run_id", ""))
    resumed["resume_source_last_stage_id"] = previous_last_stage_id
    resumed["resume_source_run_meta_path"] = norm(os.path.relpath(previous_path, repo_root))
    return resumed
