set_property(GLOBAL PROPERTY DOM_IDE_WARNINGS "")

function(dom_ide_reset_warnings)
    set_property(GLOBAL PROPERTY DOM_IDE_WARNINGS "")
endfunction()

function(dom_ide_get_warnings out_var)
    get_property(_warnings GLOBAL PROPERTY DOM_IDE_WARNINGS)
    if(NOT _warnings)
        set(_warnings "")
    endif()
    set(${out_var} "${_warnings}" PARENT_SCOPE)
endfunction()

function(dom_ide_append_warning msg)
    get_property(_warnings GLOBAL PROPERTY DOM_IDE_WARNINGS)
    if(NOT _warnings)
        set(_warnings "")
    endif()
    list(APPEND _warnings "${msg}")
    set_property(GLOBAL PROPERTY DOM_IDE_WARNINGS "${_warnings}")
endfunction()

function(dom_ide_require var_name)
    if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
        message(FATAL_ERROR "IDE projection requires ${var_name} to be set.")
    endif()
endfunction()

function(dom_ide_normalize_paths out_var)
    set(_out "")
    foreach(_path IN LISTS ARGN)
        if("${_path}" MATCHES "\\$<")
            dom_ide_append_warning("filtered_generator_expression:${_path}")
            continue()
        endif()
        if(NOT IS_ABSOLUTE "${_path}")
            set(_path "${CMAKE_SOURCE_DIR}/${_path}")
        endif()
        file(TO_CMAKE_PATH "${_path}" _path_norm)
        list(APPEND _out "${_path_norm}")
    endforeach()
    if(_out)
        list(REMOVE_DUPLICATES _out)
        list(SORT _out)
    endif()
    set(${out_var} "${_out}" PARENT_SCOPE)
endfunction()

function(dom_ide_normalize_values out_var)
    set(_out "")
    foreach(_val IN LISTS ARGN)
        if("${_val}" MATCHES "\\$<")
            dom_ide_append_warning("filtered_generator_expression:${_val}")
            continue()
        endif()
        list(APPEND _out "${_val}")
    endforeach()
    if(_out)
        list(REMOVE_DUPLICATES _out)
        list(SORT _out)
    endif()
    set(${out_var} "${_out}" PARENT_SCOPE)
endfunction()

function(dom_ide_collect_target_sources out_var target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "IDE projection target not found: ${target}")
    endif()
    get_target_property(_srcs ${target} SOURCES)
    if(_srcs STREQUAL "SOURCES-NOTFOUND")
        set(_srcs "")
    endif()
    dom_ide_normalize_paths(_norm ${_srcs})
    set(${out_var} "${_norm}" PARENT_SCOPE)
endfunction()

function(dom_ide_collect_target_includes out_var target)
    get_target_property(_incs ${target} INCLUDE_DIRECTORIES)
    get_target_property(_iface_incs ${target} INTERFACE_INCLUDE_DIRECTORIES)
    if(_incs STREQUAL "INCLUDE_DIRECTORIES-NOTFOUND")
        set(_incs "")
    endif()
    if(_iface_incs STREQUAL "INTERFACE_INCLUDE_DIRECTORIES-NOTFOUND")
        set(_iface_incs "")
    endif()
    set(_all ${_incs} ${_iface_incs})
    dom_ide_normalize_paths(_norm ${_all})
    set(${out_var} "${_norm}" PARENT_SCOPE)
endfunction()

function(dom_ide_collect_target_defines out_var target)
    get_target_property(_defs ${target} COMPILE_DEFINITIONS)
    get_target_property(_iface_defs ${target} INTERFACE_COMPILE_DEFINITIONS)
    if(_defs STREQUAL "COMPILE_DEFINITIONS-NOTFOUND")
        set(_defs "")
    endif()
    if(_iface_defs STREQUAL "INTERFACE_COMPILE_DEFINITIONS-NOTFOUND")
        set(_iface_defs "")
    endif()
    set(_all ${_defs} ${_iface_defs})
    dom_ide_normalize_values(_norm ${_all})
    set(${out_var} "${_norm}" PARENT_SCOPE)
endfunction()

function(dom_ide_collect_target_links out_var target)
    get_target_property(_links ${target} LINK_LIBRARIES)
    get_target_property(_iface_links ${target} INTERFACE_LINK_LIBRARIES)
    if(_links STREQUAL "LINK_LIBRARIES-NOTFOUND")
        set(_links "")
    endif()
    if(_iface_links STREQUAL "INTERFACE_LINK_LIBRARIES-NOTFOUND")
        set(_iface_links "")
    endif()
    set(_all ${_links} ${_iface_links})
    dom_ide_normalize_values(_norm ${_all})
    set(${out_var} "${_norm}" PARENT_SCOPE)
endfunction()

function(dom_ide_write_list_file path list_var)
    set(_content "")
    foreach(_item IN LISTS ${list_var})
        string(APPEND _content "${_item}\n")
    endforeach()
    file(WRITE "${path}" "${_content}")
endfunction()
