function(dom_ide_generate_vs out_dir)
    file(MAKE_DIRECTORY "${out_dir}")
    file(WRITE "${out_dir}/PROJECTION_GENERATOR.txt"
        "CMake generator: ${CMAKE_GENERATOR}\n"
        "VS projections are generated by CMake during configure.\n"
    )
endfunction()
