function(dom_ide_json_escape out_var value)
    set(_val "${value}")
    string(REPLACE "\\" "\\\\" _val "${_val}")
    string(REPLACE "\"" "\\\"" _val "${_val}")
    set(${out_var} "${_val}" PARENT_SCOPE)
endfunction()

function(dom_ide_json_array out_var list_name)
    set(_json "[")
    set(_first TRUE)
    foreach(_item IN LISTS ${list_name})
        dom_ide_json_escape(_esc "${_item}")
        if(NOT _first)
            string(APPEND _json ", ")
        endif()
        string(APPEND _json "\"${_esc}\"")
        set(_first FALSE)
    endforeach()
    string(APPEND _json "]")
    set(${out_var} "${_json}" PARENT_SCOPE)
endfunction()

function(dom_ide_write_manifest output_file)
    dom_ide_json_escape(_proj_id "${DOM_PROJECTION_ID}")
    dom_ide_json_escape(_product "${DOM_PRODUCT}")
    dom_ide_json_escape(_ui_shell "${DOM_UI_SHELL}")
    dom_ide_json_escape(_toolchain "${DOM_TOOLCHAIN_TIER}")
    dom_ide_json_escape(_os_family "${DOM_TARGET_OS_FAMILY}")
    dom_ide_json_escape(_os_min "${DOM_TARGET_OS_MIN}")
    dom_ide_json_escape(_arch "${DOM_TARGET_ARCH}")
    dom_ide_json_escape(_lang_mode "${DOM_LANG_MODE}")
    dom_ide_json_escape(_sdk_pin "${DOM_SDK_PIN}")
    dom_ide_json_escape(_crt_policy "${DOM_CRT_POLICY}")
    dom_ide_json_escape(_generator "${DOM_IDE_GENERATOR_NAME}")
    dom_ide_json_escape(_fingerprint "${DOM_IDE_INPUT_FINGERPRINT}")
    dom_ide_json_escape(_regen "${DOM_IDE_REGEN_COMMAND}")
    dom_ide_json_array(_output_paths_json DOM_IDE_OUTPUT_PATHS)
    dom_ide_json_array(_warnings_json DOM_IDE_WARNINGS)

    file(WRITE "${output_file}" "{\n")
    file(APPEND "${output_file}" "  \"projection_id\": \"${_proj_id}\",\n")
    file(APPEND "${output_file}" "  \"product\": \"${_product}\",\n")
    file(APPEND "${output_file}" "  \"ui_shell\": \"${_ui_shell}\",\n")
    file(APPEND "${output_file}" "  \"toolchain_tier\": \"${_toolchain}\",\n")
    file(APPEND "${output_file}" "  \"target_os_family\": \"${_os_family}\",\n")
    file(APPEND "${output_file}" "  \"target_os_min\": \"${_os_min}\",\n")
    file(APPEND "${output_file}" "  \"arch\": \"${_arch}\",\n")
    file(APPEND "${output_file}" "  \"language_mode\": \"${_lang_mode}\",\n")
    file(APPEND "${output_file}" "  \"sdk_pin\": \"${_sdk_pin}\",\n")
    file(APPEND "${output_file}" "  \"crt_policy\": \"${_crt_policy}\",\n")
    file(APPEND "${output_file}" "  \"generator\": \"${_generator}\",\n")
    file(APPEND "${output_file}" "  \"input_fingerprint\": \"${_fingerprint}\",\n")
    file(APPEND "${output_file}" "  \"output_paths\": ${_output_paths_json},\n")
    file(APPEND "${output_file}" "  \"regeneration_command\": \"${_regen}\",\n")
    file(APPEND "${output_file}" "  \"warnings\": ${_warnings_json}\n")
    file(APPEND "${output_file}" "}\n")
endfunction()

function(dom_ide_get_product_target out_var)
    if(DEFINED DOM_PRODUCT_TARGET AND NOT DOM_PRODUCT_TARGET STREQUAL "")
        set(${out_var} "${DOM_PRODUCT_TARGET}" PARENT_SCOPE)
        return()
    endif()
    if(DOM_PRODUCT STREQUAL "engine")
        set(${out_var} "domino_engine" PARENT_SCOPE)
    elseif(DOM_PRODUCT STREQUAL "game")
        set(${out_var} "dominium_game" PARENT_SCOPE)
    elseif(DOM_PRODUCT STREQUAL "client")
        set(${out_var} "dominium_client" PARENT_SCOPE)
    elseif(DOM_PRODUCT STREQUAL "server")
        set(${out_var} "dominium_server" PARENT_SCOPE)
    elseif(DOM_PRODUCT STREQUAL "launcher")
        set(${out_var} "launcher_cli" PARENT_SCOPE)
    elseif(DOM_PRODUCT STREQUAL "setup")
        set(${out_var} "setup_cli" PARENT_SCOPE)
    elseif(DOM_PRODUCT STREQUAL "tools")
        message(FATAL_ERROR "DOM_PRODUCT=tools requires DOM_PRODUCT_TARGET to be set.")
    else()
        message(FATAL_ERROR "Unknown DOM_PRODUCT '${DOM_PRODUCT}'.")
    endif()
endfunction()

function(dom_ide_generate_projection)
    dom_ide_reset_warnings()
    dom_ide_require(DOM_PROJECTION_ID)
    dom_ide_require(DOM_PRODUCT)
    dom_ide_require(DOM_UI_SHELL)
    dom_ide_require(DOM_TOOLCHAIN_TIER)
    dom_ide_require(DOM_TARGET_OS_FAMILY)
    dom_ide_require(DOM_TARGET_OS_MIN)
    dom_ide_require(DOM_TARGET_ARCH)
    dom_ide_require(DOM_LANG_MODE)
    dom_ide_require(DOM_SDK_PIN)
    dom_ide_require(DOM_CRT_POLICY)
    dom_ide_require(DOM_IDE_OUT_DIR)

    dom_ide_apply_toolchain_policy()

    dom_ide_get_product_target(_product_target)
    dom_ide_collect_target_sources(_sources ${_product_target})
    dom_ide_collect_target_includes(_includes ${_product_target})
    dom_ide_collect_target_defines(_defines ${_product_target})
    dom_ide_collect_target_links(_links ${_product_target})

    if(IS_ABSOLUTE "${DOM_IDE_OUT_DIR}")
        set(_out_dir "${DOM_IDE_OUT_DIR}")
    else()
        set(_out_dir "${CMAKE_SOURCE_DIR}/${DOM_IDE_OUT_DIR}")
    endif()
    file(TO_CMAKE_PATH "${_out_dir}" _out_dir)
    file(TO_CMAKE_PATH "${CMAKE_SOURCE_DIR}/ide" _ide_root)
    string(TOLOWER "${_out_dir}" _out_dir_lc)
    string(TOLOWER "${_ide_root}" _ide_root_lc)
    string(FIND "${_out_dir_lc}" "${_ide_root_lc}" _ide_pos)
    if(NOT _ide_pos EQUAL 0)
        message(FATAL_ERROR "DOM_IDE_OUT_DIR must be under ${_ide_root}.")
    endif()

    file(MAKE_DIRECTORY "${_out_dir}/lists")
    dom_ide_write_list_file("${_out_dir}/lists/sources.txt" _sources)
    dom_ide_write_list_file("${_out_dir}/lists/includes.txt" _includes)
    dom_ide_write_list_file("${_out_dir}/lists/defines.txt" _defines)
    dom_ide_write_list_file("${_out_dir}/lists/links.txt" _links)

    set(_payload "projection_id=${DOM_PROJECTION_ID}\n")
    string(APPEND _payload "product=${DOM_PRODUCT}\n")
    string(APPEND _payload "toolchain=${DOM_TOOLCHAIN_TIER}\n")
    string(APPEND _payload "os_family=${DOM_TARGET_OS_FAMILY}\n")
    string(APPEND _payload "os_min=${DOM_TARGET_OS_MIN}\n")
    string(APPEND _payload "arch=${DOM_TARGET_ARCH}\n")
    string(APPEND _payload "lang=${DOM_LANG_MODE}\n")
    string(APPEND _payload "sdk=${DOM_SDK_PIN}\n")
    string(APPEND _payload "crt=${DOM_CRT_POLICY}\n")
    string(APPEND _payload "generator=${CMAKE_GENERATOR}\n")
    foreach(_item IN LISTS _sources)
        string(APPEND _payload "src=${_item}\n")
    endforeach()
    foreach(_item IN LISTS _includes)
        string(APPEND _payload "inc=${_item}\n")
    endforeach()
    foreach(_item IN LISTS _defines)
        string(APPEND _payload "def=${_item}\n")
    endforeach()
    foreach(_item IN LISTS _links)
        string(APPEND _payload "link=${_item}\n")
    endforeach()
    string(SHA256 _fingerprint "${_payload}")
    set(DOM_IDE_INPUT_FINGERPRINT "sha256:${_fingerprint}")

    if(DEFINED DOM_IDE_GENERATOR_OVERRIDE AND NOT DOM_IDE_GENERATOR_OVERRIDE STREQUAL "")
        set(DOM_IDE_GENERATOR_NAME "${DOM_IDE_GENERATOR_OVERRIDE}")
    else()
        set(DOM_IDE_GENERATOR_NAME "${CMAKE_GENERATOR}")
    endif()
    set(DOM_IDE_REGEN_COMMAND "cmake --preset ${DOM_PROJECTION_ID}")

    file(RELATIVE_PATH _out_rel "${CMAKE_SOURCE_DIR}" "${_out_dir}")
    file(TO_CMAKE_PATH "${_out_rel}" _out_rel)
    set(DOM_IDE_OUTPUT_PATHS "${_out_rel}" "${_out_rel}/lists")

    if(DOM_IDE_GENERATOR_FAMILY STREQUAL "legacy_vc6")
        dom_ide_generate_legacy_vc6("${_out_dir}" "${DOM_PROJECTION_ID}" _sources)
    elseif(DOM_IDE_GENERATOR_FAMILY STREQUAL "legacy_vc71")
        dom_ide_generate_legacy_vc71("${_out_dir}" "${DOM_PROJECTION_ID}" _sources)
    elseif(DOM_IDE_GENERATOR_FAMILY STREQUAL "codewarrior")
        dom_ide_generate_codewarrior("${_out_dir}" "${DOM_PROJECTION_ID}" _sources)
    elseif(DOM_IDE_GENERATOR_FAMILY STREQUAL "vs")
        dom_ide_generate_vs("${_out_dir}")
    elseif(DOM_IDE_GENERATOR_FAMILY STREQUAL "xcode")
        dom_ide_generate_xcode("${_out_dir}")
    else()
        dom_ide_append_warning("unknown_generator_family:${DOM_IDE_GENERATOR_FAMILY}")
    endif()

    dom_ide_get_warnings(DOM_IDE_WARNINGS)

    file(MAKE_DIRECTORY "${CMAKE_SOURCE_DIR}/ide/manifests")
    dom_ide_write_manifest("${CMAKE_SOURCE_DIR}/ide/manifests/${DOM_PROJECTION_ID}.projection.json")
endfunction()
