function(dom_ide_apply_toolchain_policy)
    dom_ide_require(DOM_TOOLCHAIN_TIER)
    set(_family "")
    if(DOM_TOOLCHAIN_TIER STREQUAL "vc6")
        set(_family "legacy_vc6")
        dom_ide_append_warning("legacy tier frozen")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "vc71")
        set(_family "legacy_vc71")
        dom_ide_append_warning("legacy tier frozen")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "vs2015")
        set(_family "vs")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "vs2026")
        set(_family "vs")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "cw_classic")
        set(_family "codewarrior")
        dom_ide_append_warning("legacy tier frozen")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "xcode2")
        set(_family "xcode")
        dom_ide_append_warning("legacy tier frozen")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "xcode3")
        set(_family "xcode")
        dom_ide_append_warning("legacy tier frozen")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "xcode4_9")
        set(_family "xcode")
        dom_ide_append_warning("legacy tier frozen")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "xcode15")
        set(_family "xcode")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "gcc295")
        set(_family "legacy_gcc")
        dom_ide_append_warning("legacy tier frozen")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "gcc_legacy")
        set(_family "gcc")
    elseif(DOM_TOOLCHAIN_TIER STREQUAL "clang_modern")
        set(_family "clang")
    else()
        message(FATAL_ERROR "Unknown DOM_TOOLCHAIN_TIER '${DOM_TOOLCHAIN_TIER}'")
    endif()
    set(DOM_IDE_GENERATOR_FAMILY "${_family}" PARENT_SCOPE)
endfunction()
