"""Virtual path resolution surfaces for AppShell and runtime tools."""

from .virtual_paths import (
    VROOT_BIN,
    VROOT_EXPORTS,
    VROOT_INSTALL,
    VROOT_INSTANCES,
    VROOT_IPC,
    VROOT_LOCKS,
    VROOT_LOGS,
    VROOT_PACKS,
    VROOT_PROFILES,
    VROOT_SAVES,
    VROOT_STORE,
    clear_current_virtual_paths,
    get_current_virtual_paths,
    load_virtual_root_registry,
    set_current_virtual_paths,
    vpath_candidate_roots,
    vpath_exists,
    vpath_init,
    vpath_list,
    vpath_open_read,
    vpath_open_write,
    vpath_resolve,
    vpath_resolve_existing,
    vpath_root,
)

__all__ = [
    "VROOT_BIN",
    "VROOT_EXPORTS",
    "VROOT_INSTALL",
    "VROOT_INSTANCES",
    "VROOT_IPC",
    "VROOT_LOCKS",
    "VROOT_LOGS",
    "VROOT_PACKS",
    "VROOT_PROFILES",
    "VROOT_SAVES",
    "VROOT_STORE",
    "clear_current_virtual_paths",
    "get_current_virtual_paths",
    "load_virtual_root_registry",
    "set_current_virtual_paths",
    "vpath_candidate_roots",
    "vpath_exists",
    "vpath_init",
    "vpath_list",
    "vpath_open_read",
    "vpath_open_write",
    "vpath_resolve",
    "vpath_resolve_existing",
    "vpath_root",
]
