"""ELEC-1 package exports."""

from .fault import (
    REFUSAL_ELEC_FAULT_INVALID,
    ElectricFaultError,
    build_fault_state,
    detect_faults,
    fault_kind_rows_by_id,
    grounding_policy_rows_by_id,
    normalize_fault_state_rows,
)
from .protection import (
    REFUSAL_ELEC_PROTECTION_INVALID,
    ElectricProtectionError,
    build_protection_device,
    build_protection_settings,
    coordination_policy_rows_by_id,
    deterministic_protection_device_id,
    evaluate_protection_trip_plan,
    normalize_protection_device_rows,
    normalize_protection_settings_rows,
    protection_device_kind_rows_by_id,
)
from .storage import (
    REFUSAL_ELEC_STORAGE_INVALID,
    ElectricStorageError,
    SOC_SCALE,
    apply_storage_charge,
    apply_storage_discharge,
    build_storage_state,
    normalize_storage_state_rows,
    storage_state_rows_by_node_id,
)
from .power_network_engine import (
    ElectricError,
    REFUSAL_ELEC_NETWORK_INVALID,
    REFUSAL_ELEC_SPEC_NONCOMPLIANT,
    build_power_flow_channel,
    compute_pf_permille,
    deterministic_power_channel_id,
    evaluate_connection_spec_compatibility,
    normalize_elec_edge_payload,
    normalize_elec_node_payload,
    solve_power_network_e0,
    solve_power_network_e1,
)

__all__ = [
    "REFUSAL_ELEC_FAULT_INVALID",
    "ElectricFaultError",
    "build_fault_state",
    "detect_faults",
    "fault_kind_rows_by_id",
    "grounding_policy_rows_by_id",
    "normalize_fault_state_rows",
    "REFUSAL_ELEC_PROTECTION_INVALID",
    "ElectricProtectionError",
    "build_protection_device",
    "build_protection_settings",
    "coordination_policy_rows_by_id",
    "deterministic_protection_device_id",
    "evaluate_protection_trip_plan",
    "normalize_protection_device_rows",
    "normalize_protection_settings_rows",
    "protection_device_kind_rows_by_id",
    "REFUSAL_ELEC_STORAGE_INVALID",
    "ElectricStorageError",
    "SOC_SCALE",
    "apply_storage_charge",
    "apply_storage_discharge",
    "build_storage_state",
    "normalize_storage_state_rows",
    "storage_state_rows_by_node_id",
    "ElectricError",
    "REFUSAL_ELEC_NETWORK_INVALID",
    "REFUSAL_ELEC_SPEC_NONCOMPLIANT",
    "build_power_flow_channel",
    "compute_pf_permille",
    "deterministic_power_channel_id",
    "evaluate_connection_spec_compatibility",
    "normalize_elec_edge_payload",
    "normalize_elec_node_payload",
    "solve_power_network_e0",
    "solve_power_network_e1",
]
