/*
FILE: libs/appcore/command/command_registry.h
MODULE: Dominium
PURPOSE: Canonical application command registry (data-only descriptors).
NOTES: CLI is canonical; GUI binds to this registry.
*/
#ifndef DOMINIUM_APPCORE_COMMAND_REGISTRY_H
#define DOMINIUM_APPCORE_COMMAND_REGISTRY_H

#include "domino/core/types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* command identifiers (stable; append-only). */
typedef enum dom_app_command_id_e {
    DOM_APP_CMD_INVALID = 0,
    DOM_APP_CMD_LAUNCHER_VERSION,
    DOM_APP_CMD_LAUNCHER_LIST_PROFILES,
    DOM_APP_CMD_LAUNCHER_CAPABILITIES,
    DOM_APP_CMD_LAUNCHER_NEW_WORLD,
    DOM_APP_CMD_LAUNCHER_LOAD_WORLD,
    DOM_APP_CMD_LAUNCHER_INSPECT_REPLAY,
    DOM_APP_CMD_LAUNCHER_INSTALLS,
    DOM_APP_CMD_LAUNCHER_INSTANCES,
    DOM_APP_CMD_LAUNCHER_PROFILES,
    DOM_APP_CMD_LAUNCHER_PREFLIGHT,
    DOM_APP_CMD_LAUNCHER_RUN,
    DOM_APP_CMD_LAUNCHER_PACKS,
    DOM_APP_CMD_LAUNCHER_BUNDLES,
    DOM_APP_CMD_LAUNCHER_PATHS,
    DOM_APP_CMD_LAUNCHER_OPS,
    DOM_APP_CMD_LAUNCHER_SHARE,
    DOM_APP_CMD_LAUNCHER_BUGREPORT,
    DOM_APP_CMD_LAUNCHER_TOOLS,
    DOM_APP_CMD_LAUNCHER_SETTINGS,
    DOM_APP_CMD_LAUNCHER_EXIT,

    DOM_APP_CMD_SETUP_VERSION,
    DOM_APP_CMD_SETUP_STATUS,
    DOM_APP_CMD_SETUP_PREPARE,
    DOM_APP_CMD_SETUP_INSTALL,
    DOM_APP_CMD_SETUP_REPAIR,
    DOM_APP_CMD_SETUP_UNINSTALL,
    DOM_APP_CMD_SETUP_ROLLBACK,
    DOM_APP_CMD_SETUP_EXPORT_INVOCATION,
    DOM_APP_CMD_SETUP_PLAN,
    DOM_APP_CMD_SETUP_APPLY,
    DOM_APP_CMD_SETUP_DETECT,
    DOM_APP_CMD_SETUP_MANIFEST,
    DOM_APP_CMD_SETUP_OPS,
    DOM_APP_CMD_SETUP_SHARE,

    DOM_APP_CMD_CLIENT_NEW_WORLD,
    DOM_APP_CMD_CLIENT_CREATE_WORLD,
    DOM_APP_CMD_CLIENT_LOAD_WORLD,
    DOM_APP_CMD_CLIENT_SCENARIO_LOAD,
    DOM_APP_CMD_CLIENT_INSPECT_REPLAY,
    DOM_APP_CMD_CLIENT_SAVE,
    DOM_APP_CMD_CLIENT_REPLAY_SAVE,
    DOM_APP_CMD_CLIENT_PROFILE_NEXT,
    DOM_APP_CMD_CLIENT_PROFILE_PREV,
    DOM_APP_CMD_CLIENT_PRESET_NEXT,
    DOM_APP_CMD_CLIENT_PRESET_PREV,
    DOM_APP_CMD_CLIENT_ACCESSIBILITY_NEXT,
    DOM_APP_CMD_CLIENT_KEYBIND_NEXT,
    DOM_APP_CMD_CLIENT_REPLAY_STEP,
    DOM_APP_CMD_CLIENT_REPLAY_REWIND,
    DOM_APP_CMD_CLIENT_REPLAY_PAUSE,
    DOM_APP_CMD_CLIENT_TEMPLATES,
    DOM_APP_CMD_CLIENT_MODE,
    DOM_APP_CMD_CLIENT_MOVE,
    DOM_APP_CMD_CLIENT_SPAWN,
    DOM_APP_CMD_CLIENT_CAMERA,
    DOM_APP_CMD_CLIENT_CAMERA_NEXT,
    DOM_APP_CMD_CLIENT_INSPECT_TOGGLE,
    DOM_APP_CMD_CLIENT_HUD_TOGGLE,
    DOM_APP_CMD_CLIENT_DOMAIN,
    DOM_APP_CMD_CLIENT_WHERE,
    DOM_APP_CMD_CLIENT_SIMULATE,
    DOM_APP_CMD_CLIENT_AGENTS,
    DOM_APP_CMD_CLIENT_AGENT_ADD,
    DOM_APP_CMD_CLIENT_GOALS,
    DOM_APP_CMD_CLIENT_GOAL_ADD,
    DOM_APP_CMD_CLIENT_DELEGATE,
    DOM_APP_CMD_CLIENT_DELEGATIONS,
    DOM_APP_CMD_CLIENT_AUTHORITY_GRANT,
    DOM_APP_CMD_CLIENT_AUTHORITY_LIST,
    DOM_APP_CMD_CLIENT_CONSTRAINT_ADD,
    DOM_APP_CMD_CLIENT_CONSTRAINT_LIST,
    DOM_APP_CMD_CLIENT_INSTITUTION_CREATE,
    DOM_APP_CMD_CLIENT_INSTITUTION_LIST,
    DOM_APP_CMD_CLIENT_NETWORK_CREATE,
    DOM_APP_CMD_CLIENT_NETWORK_LIST,
    DOM_APP_CMD_CLIENT_TOOLS,
    DOM_APP_CMD_CLIENT_SETTINGS,
    DOM_APP_CMD_CLIENT_EXIT,

    DOM_APP_CMD_TOOLS_INSPECT,
    DOM_APP_CMD_TOOLS_VALIDATE,
    DOM_APP_CMD_TOOLS_REPLAY,
    DOM_APP_CMD_TOOLS_NEW_WORLD,
    DOM_APP_CMD_TOOLS_LOAD_WORLD,
    DOM_APP_CMD_TOOLS_INSPECT_REPLAY,
    DOM_APP_CMD_TOOLS_SNAPSHOT_VIEWER,
    DOM_APP_CMD_TOOLS_TOOLS_MENU,
    DOM_APP_CMD_TOOLS_SETTINGS,
    DOM_APP_CMD_TOOLS_WORLD_INSPECTOR,
    DOM_APP_CMD_TOOLS_HISTORY_VIEWER,
    DOM_APP_CMD_TOOLS_TEMPLATE_TOOLS,
    DOM_APP_CMD_TOOLS_PACK_INSPECTOR,
    DOM_APP_CMD_TOOLS_WORLDDEF,
    DOM_APP_CMD_TOOLS_SCALE,
    DOM_APP_CMD_TOOLS_MMO,
    DOM_APP_CMD_TOOLS_OPS,
    DOM_APP_CMD_TOOLS_AI,
    DOM_APP_CMD_TOOLS_SHARE,
    DOM_APP_CMD_TOOLS_EXIT,

    DOM_APP_CMD_LAUNCHER_UI_NAV_PLAY,
    DOM_APP_CMD_LAUNCHER_UI_NAV_INSTANCES,
    DOM_APP_CMD_LAUNCHER_UI_NAV_SETTINGS,
    DOM_APP_CMD_LAUNCHER_UI_NAV_MODS,
    DOM_APP_CMD_LAUNCHER_UI_INSTANCES_SELECT,
    DOM_APP_CMD_LAUNCHER_UI_INSTANCES_PLAY_SELECTED,
    DOM_APP_CMD_LAUNCHER_UI_INSTANCES_EDIT_SELECTED,
    DOM_APP_CMD_LAUNCHER_UI_INSTANCES_DELETE_SELECTED,
    DOM_APP_CMD_LAUNCHER_UI_SETTINGS_APPLY,

    DOM_APP_CMD_SETUP_UI_BROWSE_PATH,
    DOM_APP_CMD_SETUP_UI_OPTIONS_CHANGED,
    DOM_APP_CMD_SETUP_UI_NAV_BACK,
    DOM_APP_CMD_SETUP_UI_NAV_NEXT,
    DOM_APP_CMD_SETUP_UI_NAV_INSTALL,
    DOM_APP_CMD_SETUP_UI_NAV_FINISH,
    DOM_APP_CMD_SETUP_UI_NAV_CANCEL,

    DOM_APP_CMD_TOOL_EDITOR_UI_TAB_CHANGE,
    DOM_APP_CMD_TOOL_EDITOR_UI_NEW,
    DOM_APP_CMD_TOOL_EDITOR_UI_OPEN,
    DOM_APP_CMD_TOOL_EDITOR_UI_SAVE,
    DOM_APP_CMD_TOOL_EDITOR_UI_SAVE_AS,
    DOM_APP_CMD_TOOL_EDITOR_UI_VALIDATE,
    DOM_APP_CMD_TOOL_EDITOR_UI_ADD_WIDGET,
    DOM_APP_CMD_TOOL_EDITOR_UI_DELETE_WIDGET,
    DOM_APP_CMD_TOOL_EDITOR_UI_HIERARCHY_SELECT,
    DOM_APP_CMD_TOOL_EDITOR_UI_PROP_NAME,
    DOM_APP_CMD_TOOL_EDITOR_UI_PROP_X,
    DOM_APP_CMD_TOOL_EDITOR_UI_PROP_Y,
    DOM_APP_CMD_TOOL_EDITOR_UI_PROP_W,
    DOM_APP_CMD_TOOL_EDITOR_UI_PROP_H,
    DOM_APP_CMD_CLIENT_UI_NAV_PLAY,
    DOM_APP_CMD_SERVER_UI_STATUS
} dom_app_command_id;

/* canonical epistemic command scopes. */
#define DOM_EPISTEMIC_SCOPE_OBS_ONLY "obs_only"
#define DOM_EPISTEMIC_SCOPE_MEMORY_ONLY "memory_only"
#define DOM_EPISTEMIC_SCOPE_PARTIAL "partial"
#define DOM_EPISTEMIC_SCOPE_FULL "full"

/* Minimal argument schema tokens. */
#define DOM_APP_ARG_SCHEMA_NONE "none"
#define DOM_APP_ARG_SCHEMA_ARGS "argv"
#define DOM_APP_ARG_SCHEMA_PATH "path"
#define DOM_APP_ARG_SCHEMA_INSTANCE_ID "instance_id"
#define DOM_APP_ARG_SCHEMA_SUBCOMMAND "subcommand"

/* Command descriptor (data-only). */
typedef struct dom_app_command_desc_t {
    u32 command_id;
    const char* name;
    const char* owning_app;      /* launcher|setup|client|server|tools */
    const char* arg_schema;      /* schema token (no defaults) */
    const char* const* failure_codes;
    u32 failure_code_count;
    const int* exit_codes;
    u32 exit_code_count;
    const char* const* required_capabilities; /* explicit list, may be empty */
    u32 required_capability_count;
    const char* epistemic_scope;              /* one of DOM_EPISTEMIC_SCOPE_* */
} dom_app_command_desc;

const dom_app_command_desc* appcore_command_registry(u32* out_count);
const dom_app_command_desc* appcore_command_find(const char* name);
int appcore_dispatch_command(const dom_app_command_desc* cmd);
int appcore_command_capabilities_allowed(const dom_app_command_desc* cmd,
                                         const char* const* capability_ids,
                                         u32 capability_count);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DOMINIUM_APPCORE_COMMAND_REGISTRY_H */
