#ifndef DSK_CONTRACT_PLAN_H
#define DSK_CONTRACT_PLAN_H

#include "dsk_tlv.h"

/* Plan tags (0x5000 range) */
#define DSK_TLV_TAG_PLAN_PRODUCT_ID 0x5001u
#define DSK_TLV_TAG_PLAN_PRODUCT_VERSION 0x5002u
#define DSK_TLV_TAG_PLAN_SELECTED_SPLAT_ID 0x5003u
#define DSK_TLV_TAG_PLAN_SELECTED_SPLAT_CAPS_DIGEST64 0x5004u
#define DSK_TLV_TAG_PLAN_OPERATION 0x5005u
#define DSK_TLV_TAG_PLAN_INSTALL_SCOPE 0x5006u
#define DSK_TLV_TAG_PLAN_INSTALL_ROOTS 0x5007u
#define DSK_TLV_TAG_PLAN_MANIFEST_DIGEST64 0x5008u
#define DSK_TLV_TAG_PLAN_REQUEST_DIGEST64 0x5009u
#define DSK_TLV_TAG_PLAN_RESOLVED_SET_DIGEST64 0x500Au
#define DSK_TLV_TAG_PLAN_DIGEST64 0x500Bu
#define DSK_TLV_TAG_PLAN_RESOLVED_COMPONENTS 0x500Cu
#define DSK_TLV_TAG_PLAN_JOB_GRAPH 0x500Du
#define DSK_TLV_TAG_PLAN_FILE_OPS 0x500Eu
#define DSK_TLV_TAG_PLAN_REGISTRATIONS 0x500Fu

#define DSK_TLV_TAG_PLAN_INSTALL_ROOT_ENTRY 0x5010u

#define DSK_TLV_TAG_PLAN_COMPONENT_ENTRY 0x5101u
#define DSK_TLV_TAG_PLAN_COMPONENT_ID 0x5102u
#define DSK_TLV_TAG_PLAN_COMPONENT_VERSION 0x5103u
#define DSK_TLV_TAG_PLAN_COMPONENT_KIND 0x5104u
#define DSK_TLV_TAG_PLAN_COMPONENT_SOURCE 0x5105u

#define DSK_TLV_TAG_PLAN_STEP_ENTRY 0x5201u
#define DSK_TLV_TAG_PLAN_STEP_ID 0x5202u
#define DSK_TLV_TAG_PLAN_STEP_KIND 0x5203u
#define DSK_TLV_TAG_PLAN_STEP_COMPONENT_ID 0x5204u
#define DSK_TLV_TAG_PLAN_STEP_ARTIFACT_ID 0x5205u
#define DSK_TLV_TAG_PLAN_STEP_TARGET_ROOT_ID 0x5206u
#define DSK_TLV_TAG_PLAN_STEP_INTENT 0x5207u

#define DSK_TLV_TAG_PLAN_FILE_OP_ENTRY 0x5301u
#define DSK_TLV_TAG_PLAN_FILE_OP_KIND 0x5302u
#define DSK_TLV_TAG_PLAN_FILE_OP_FROM 0x5303u
#define DSK_TLV_TAG_PLAN_FILE_OP_TO 0x5304u
#define DSK_TLV_TAG_PLAN_FILE_OP_OWNERSHIP 0x5305u
#define DSK_TLV_TAG_PLAN_FILE_OP_DIGEST64 0x5306u
#define DSK_TLV_TAG_PLAN_FILE_OP_SIZE 0x5307u

#define DSK_TLV_TAG_PLAN_REG_SHORTCUTS 0x5401u
#define DSK_TLV_TAG_PLAN_REG_FILE_ASSOCS 0x5402u
#define DSK_TLV_TAG_PLAN_REG_URL_HANDLERS 0x5403u
#define DSK_TLV_TAG_PLAN_REG_SHORTCUT_ENTRY 0x5410u
#define DSK_TLV_TAG_PLAN_REG_FILE_ASSOC_ENTRY 0x5411u
#define DSK_TLV_TAG_PLAN_REG_URL_HANDLER_ENTRY 0x5412u

/* Plan enums */
#define DSK_PLAN_COMPONENT_SOURCE_DEFAULT 1u
#define DSK_PLAN_COMPONENT_SOURCE_USER 2u
#define DSK_PLAN_COMPONENT_SOURCE_DEPENDENCY 3u
#define DSK_PLAN_COMPONENT_SOURCE_INSTALLED 4u

#define DSK_PLAN_STEP_STAGE_ARTIFACT 1u
#define DSK_PLAN_STEP_VERIFY_HASHES 2u
#define DSK_PLAN_STEP_COMMIT_SWAP 3u
#define DSK_PLAN_STEP_REGISTER_ACTIONS 4u
#define DSK_PLAN_STEP_WRITE_STATE 5u
#define DSK_PLAN_STEP_WRITE_AUDIT 6u

#define DSK_PLAN_FILE_OP_COPY 1u
#define DSK_PLAN_FILE_OP_EXTRACT 2u
#define DSK_PLAN_FILE_OP_REMOVE 3u
#define DSK_PLAN_FILE_OP_MKDIR 4u

#endif /* DSK_CONTRACT_PLAN_H */
