/*
FILE: source/dominium/tools/coredata_compile/coredata_schema.h
MODULE: Dominium
PURPOSE: Coredata compiler schema constants (record type ids, tags, enums).
*/
#ifndef DOMINIUM_TOOLS_COREDATA_SCHEMA_H
#define DOMINIUM_TOOLS_COREDATA_SCHEMA_H

#include "domino/core/types.h"

/* Record type IDs (u32, stable). */
enum {
    CORE_DATA_REC_PACK_META       = 0x00000001u,
    CORE_DATA_REC_COSMO_ANCHOR    = 0x00010001u,
    CORE_DATA_REC_COSMO_EDGE      = 0x00010002u,
    CORE_DATA_REC_COSMO_RULES     = 0x00010003u,
    CORE_DATA_REC_MECH_SYSTEM     = 0x00020001u,
    CORE_DATA_REC_MECH_SITE       = 0x00020002u,
    CORE_DATA_REC_ASTRO_BODY      = 0x00030001u
};

/* Record chunk schema version (u16). */
enum { CORE_DATA_REC_VERSION_V1 = 1u };

/* Pack meta payload tags. */
enum {
    CORE_DATA_META_TAG_PACK_SCHEMA_VERSION = 1u,
    CORE_DATA_META_TAG_PACK_ID = 2u,
    CORE_DATA_META_TAG_PACK_VERSION_NUM = 3u,
    CORE_DATA_META_TAG_PACK_VERSION_STR = 4u,
    CORE_DATA_META_TAG_CONTENT_HASH = 5u
};

/* COSMO_ANCHOR_NODE payload tags. */
enum {
    CORE_DATA_ANCHOR_TAG_ID = 1u,
    CORE_DATA_ANCHOR_TAG_ID_HASH = 2u,
    CORE_DATA_ANCHOR_TAG_KIND = 3u,
    CORE_DATA_ANCHOR_TAG_DISPLAY_NAME = 4u,
    CORE_DATA_ANCHOR_TAG_SYSTEM_CLASS = 5u,
    CORE_DATA_ANCHOR_TAG_REGION_TYPE = 6u,
    CORE_DATA_ANCHOR_TAG_EVIDENCE_GRADE = 7u,
    CORE_DATA_ANCHOR_TAG_MECH_PROFILE_ID = 8u,
    CORE_DATA_ANCHOR_TAG_ANCHOR_WEIGHT = 9u,
    CORE_DATA_ANCHOR_TAG_TAG = 10u,
    CORE_DATA_ANCHOR_TAG_PRESENTATION_POS = 11u
};

/* COSMO_EDGE payload tags. */
enum {
    CORE_DATA_EDGE_TAG_SRC_ID = 1u,
    CORE_DATA_EDGE_TAG_SRC_ID_HASH = 2u,
    CORE_DATA_EDGE_TAG_DST_ID = 3u,
    CORE_DATA_EDGE_TAG_DST_ID_HASH = 4u,
    CORE_DATA_EDGE_TAG_DURATION_TICKS = 5u,
    CORE_DATA_EDGE_TAG_COST_PROFILE_ID = 6u,
    CORE_DATA_EDGE_TAG_COST_PROFILE_HASH = 7u,
    CORE_DATA_EDGE_TAG_HAZARD_PROFILE_ID = 8u,
    CORE_DATA_EDGE_TAG_HAZARD_PROFILE_HASH = 9u
};

/* COSMO_PROCEDURAL_RULES payload tags. */
enum {
    CORE_DATA_RULES_TAG_SYS_MIN = 1u,
    CORE_DATA_RULES_TAG_SYS_MAX = 2u,
    CORE_DATA_RULES_TAG_RED_DWARF_RATIO = 3u,
    CORE_DATA_RULES_TAG_BINARY_RATIO = 4u,
    CORE_DATA_RULES_TAG_EXOTIC_RATIO = 5u,
    CORE_DATA_RULES_TAG_CLUSTER_DENSITY = 6u,
    CORE_DATA_RULES_TAG_METALLICITY_BIAS = 7u,
    CORE_DATA_RULES_TAG_HAZARD_FREQUENCY = 8u
};

enum {
    CORE_DATA_RULES_ENTRY_TAG_REGION_TYPE = 1u,
    CORE_DATA_RULES_ENTRY_TAG_VALUE_Q16 = 2u
};

/* MECH_SYSTEM_PROFILE payload tags. */
enum {
    CORE_DATA_MECH_SYS_TAG_ID = 1u,
    CORE_DATA_MECH_SYS_TAG_ID_HASH = 2u,
    CORE_DATA_MECH_SYS_TAG_NAV_INSTABILITY = 3u,
    CORE_DATA_MECH_SYS_TAG_DEBRIS_COLLISION = 4u,
    CORE_DATA_MECH_SYS_TAG_RADIATION_BASELINE = 5u,
    CORE_DATA_MECH_SYS_TAG_WARP_CAP = 6u,
    CORE_DATA_MECH_SYS_TAG_SURVEY_DIFFICULTY = 7u,
    CORE_DATA_MECH_SYS_TAG_SUPERNOVA_TICKS = 8u
};

/* MECH_SITE_PROFILE payload tags. */
enum {
    CORE_DATA_MECH_SITE_TAG_ID = 1u,
    CORE_DATA_MECH_SITE_TAG_ID_HASH = 2u,
    CORE_DATA_MECH_SITE_TAG_HAZARD_RAD = 3u,
    CORE_DATA_MECH_SITE_TAG_HAZARD_PRESS = 4u,
    CORE_DATA_MECH_SITE_TAG_CORROSION_RATE = 5u,
    CORE_DATA_MECH_SITE_TAG_TEMP_EXTREME = 6u,
    CORE_DATA_MECH_SITE_TAG_RESOURCE_YIELD = 7u,
    CORE_DATA_MECH_SITE_TAG_ACCESS_CONSTRAINT = 8u
};

enum {
    CORE_DATA_MECH_SITE_RES_TAG_ID = 1u,
    CORE_DATA_MECH_SITE_RES_TAG_MOD_Q16 = 2u
};

/* ASTRO_BODY_CONSTANTS payload tags. */
enum {
    CORE_DATA_ASTRO_TAG_ID = 1u,
    CORE_DATA_ASTRO_TAG_ID_HASH = 2u,
    CORE_DATA_ASTRO_TAG_RADIUS_M = 3u,
    CORE_DATA_ASTRO_TAG_MU_MANTISSA = 4u,
    CORE_DATA_ASTRO_TAG_MU_EXP10 = 5u,
    CORE_DATA_ASTRO_TAG_ROT_RATE_Q16 = 6u,
    CORE_DATA_ASTRO_TAG_ATMOS_PROFILE_ID = 7u
};

/* Enums (stable). */
enum {
    CORE_DATA_KIND_SYSTEM = 1u,
    CORE_DATA_KIND_REGION = 2u
};

enum {
    CORE_DATA_SYSTEM_SINGLE = 1u,
    CORE_DATA_SYSTEM_BINARY = 2u,
    CORE_DATA_SYSTEM_CLUSTER = 3u,
    CORE_DATA_SYSTEM_REMNANT = 4u,
    CORE_DATA_SYSTEM_EXOTIC = 5u
};

enum {
    CORE_DATA_REGION_NEBULA = 1u,
    CORE_DATA_REGION_OPEN_CLUSTER = 2u,
    CORE_DATA_REGION_GLOBULAR_CLUSTER = 3u,
    CORE_DATA_REGION_GALACTIC_CORE = 4u
};

enum {
    CORE_DATA_EVIDENCE_CONFIRMED = 1u,
    CORE_DATA_EVIDENCE_CANDIDATE = 2u,
    CORE_DATA_EVIDENCE_HISTORICAL = 3u,
    CORE_DATA_EVIDENCE_FICTIONALIZED = 4u
};

#endif /* DOMINIUM_TOOLS_COREDATA_SCHEMA_H */
