"""A8 Derived artifact freshness smell analyzer."""

import json
import os
import re

from analyzers.base import make_finding


ANALYZER_ID = "A8_DERIVED_FRESHNESS_SMELL"
DERIVED_HEADER_RE = re.compile(r"^Status:\s*DERIVED\s*$", re.MULTILINE | re.IGNORECASE)
LAST_REVIEWED_RE = re.compile(r"^Last Reviewed:\s*([0-9]{4}-[0-9]{2}-[0-9]{2})\s*$", re.MULTILINE)
GENERATOR_HINT_RE = re.compile(r"\b(generated by|generator|tool_[a-z0-9_]+|scripts?/)\b", re.IGNORECASE)
SOURCE_EXTS = (".md", ".json", ".txt")


def _read_text(path):
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as handle:
            return handle.read()
    except OSError:
        return ""


def _iter_candidate_docs(graph):
    for node in sorted(graph.nodes.values(), key=lambda item: item.label):
        if node.node_type != "file":
            continue
        rel = node.label
        if not rel.startswith("docs/"):
            continue
        if not rel.lower().endswith(SOURCE_EXTS):
            continue
        yield rel


def _derived_registry_artifacts(repo_root):
    rel = "data/registries/derived_artifacts.json"
    abs_path = os.path.join(repo_root, rel.replace("/", os.sep))
    if not os.path.isfile(abs_path):
        return []
    try:
        payload = json.load(open(abs_path, "r", encoding="utf-8"))
    except (OSError, ValueError):
        return []
    rows = (((payload.get("record") or {}).get("artifacts")) or [])
    if not isinstance(rows, list):
        return []
    out = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        out.append(
            {
                "artifact_id": str(row.get("artifact_id", "")).strip(),
                "path": str(row.get("path", "")).replace("\\", "/").strip(),
                "regeneration_tool": str(row.get("regeneration_tool", "")).strip(),
                "regenerable": bool(row.get("regenerable", False)),
            }
        )
    return sorted(out, key=lambda item: (item["path"], item["artifact_id"]))


def _derived_pack_jsons(repo_root):
    root = os.path.join(repo_root, "packs", "derived")
    out = []
    if not os.path.isdir(root):
        return out
    for walk_root, dirs, files in os.walk(root):
        dirs[:] = sorted(dirs)
        for name in sorted(files):
            if not str(name).lower().endswith(".json"):
                continue
            if str(name).lower() == "pack.json":
                continue
            abs_path = os.path.join(walk_root, name)
            rel_path = str(os.path.relpath(abs_path, repo_root)).replace("\\", "/")
            out.append(rel_path)
    return sorted(set(out))


def run(graph, repo_root, changed_files=None):
    del changed_files
    findings = []

    for rel in _iter_candidate_docs(graph):
        text = _read_text(os.path.join(repo_root, rel.replace("/", os.sep)))
        if not DERIVED_HEADER_RE.search(text):
            continue
        has_last_review = bool(LAST_REVIEWED_RE.search(text))
        has_generator_hint = bool(GENERATOR_HINT_RE.search(text))

        if not has_last_review:
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="WARN",
                    confidence=0.80,
                    file_path=rel,
                    evidence=[
                        "Derived artifact is missing a Last Reviewed header field.",
                        "Freshness tracking may drift without timestamp metadata.",
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="DOC_FIX",
                    related_invariants=["INV-DOC-STATUS-HEADER"],
                    related_paths=[rel],
                )
            )

        if not has_generator_hint:
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="INFO",
                    confidence=0.55,
                    file_path=rel,
                    evidence=[
                        "Derived artifact lacks obvious generator/source command reference.",
                        "Add deterministic regeneration hint to improve freshness governance.",
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="ADD_RULE",
                    related_invariants=["INV-DERIVED-ARTIFACT-FRESHNESS"],
                    related_paths=[rel],
                )
            )

        if len(findings) >= 120:
            break

    registry_rows = _derived_registry_artifacts(repo_root)
    for row in registry_rows:
        rel = str(row.get("path", ""))
        if not rel:
            continue
        abs_path = os.path.join(repo_root, rel.replace("/", os.sep))
        if not os.path.isfile(abs_path):
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="RISK",
                    confidence=0.76,
                    file_path=rel,
                    evidence=[
                        "Derived artifact listed in registry is missing on disk.",
                        "artifact_id={}".format(str(row.get("artifact_id", ""))),
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="ADD_RULE",
                    related_invariants=["INV-DERIVED-ARTIFACT-FRESHNESS"],
                    related_paths=[rel],
                )
            )
            continue
        if bool(row.get("regenerable", False)) and not str(row.get("regeneration_tool", "")).strip():
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="WARN",
                    confidence=0.63,
                    file_path=rel,
                    evidence=[
                        "Derived artifact is marked regenerable but has no regeneration_tool.",
                        "artifact_id={}".format(str(row.get("artifact_id", ""))),
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="DOC_FIX",
                    related_invariants=["INV-DERIVED-ARTIFACT-FRESHNESS"],
                    related_paths=[rel],
                )
            )

        if len(findings) >= 220:
            break

    for rel in _derived_pack_jsons(repo_root):
        abs_path = os.path.join(repo_root, rel.replace("/", os.sep))
        try:
            payload = json.load(open(abs_path, "r", encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if not isinstance(payload, dict):
            continue
        provenance = payload.get("provenance")
        if not isinstance(provenance, dict):
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="RISK",
                    confidence=0.84,
                    file_path=rel,
                    evidence=[
                        "Derived pack JSON artifact has no provenance object.",
                        "Expected deterministic source->derived traceability header.",
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="ADD_RULE",
                    related_invariants=["INV-DERIVED-HAS-PROVENANCE"],
                    related_paths=[rel],
                )
            )
            continue
        generator_tool = str(provenance.get("generator_tool_id", "")).strip()
        if not generator_tool:
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="WARN",
                    confidence=0.72,
                    file_path=rel,
                    evidence=[
                        "Derived pack JSON provenance is missing generator_tool_id.",
                        "Cannot trace deterministic regeneration tool.",
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="DOC_FIX",
                    related_invariants=["INV-DERIVED-HAS-PROVENANCE"],
                    related_paths=[rel],
                )
            )
        if len(findings) >= 260:
            break

    return sorted(findings, key=lambda item: (item.location.file_path, item.severity, item.confidence))
