"""A8 Derived artifact freshness smell analyzer."""

import os
import re

from analyzers.base import make_finding


ANALYZER_ID = "A8_DERIVED_FRESHNESS_SMELL"
DERIVED_HEADER_RE = re.compile(r"^Status:\s*DERIVED\s*$", re.MULTILINE | re.IGNORECASE)
LAST_REVIEWED_RE = re.compile(r"^Last Reviewed:\s*([0-9]{4}-[0-9]{2}-[0-9]{2})\s*$", re.MULTILINE)
GENERATOR_HINT_RE = re.compile(r"\b(generated by|generator|tool_[a-z0-9_]+|scripts?/)\b", re.IGNORECASE)
SOURCE_EXTS = (".md", ".json", ".txt")


def _read_text(path):
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as handle:
            return handle.read()
    except OSError:
        return ""


def _iter_candidate_docs(graph):
    for node in sorted(graph.nodes.values(), key=lambda item: item.label):
        if node.node_type != "file":
            continue
        rel = node.label
        if not rel.startswith("docs/"):
            continue
        if not rel.lower().endswith(SOURCE_EXTS):
            continue
        yield rel


def run(graph, repo_root, changed_files=None):
    del changed_files
    findings = []

    for rel in _iter_candidate_docs(graph):
        text = _read_text(os.path.join(repo_root, rel.replace("/", os.sep)))
        if not DERIVED_HEADER_RE.search(text):
            continue
        has_last_review = bool(LAST_REVIEWED_RE.search(text))
        has_generator_hint = bool(GENERATOR_HINT_RE.search(text))

        if not has_last_review:
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="WARN",
                    confidence=0.80,
                    file_path=rel,
                    evidence=[
                        "Derived artifact is missing a Last Reviewed header field.",
                        "Freshness tracking may drift without timestamp metadata.",
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="DOC_FIX",
                    related_invariants=["INV-DOC-STATUS-HEADER"],
                    related_paths=[rel],
                )
            )

        if not has_generator_hint:
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="INFO",
                    confidence=0.55,
                    file_path=rel,
                    evidence=[
                        "Derived artifact lacks obvious generator/source command reference.",
                        "Add deterministic regeneration hint to improve freshness governance.",
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="ADD_RULE",
                    related_invariants=["INV-DERIVED-ARTIFACT-FRESHNESS"],
                    related_paths=[rel],
                )
            )

        if len(findings) >= 120:
            break

    watch_files = (
        "data/registries/command_registry.json",
        "data/registries/capability_registry.json",
        "schema/ui/ui_ir.schema",
        "schema/distribution/pkg_manifest.schema",
    )
    manifest_files = (
        "docs/audit/auditx/FINDINGS.json",
        "docs/audit/auditx/SUMMARY.md",
    )
    for watch in watch_files:
        if not any(node.label == watch for node in graph.nodes.values() if node.node_type == "file"):
            continue
        for manifest in manifest_files:
            if any(node.label == manifest for node in graph.nodes.values() if node.node_type == "file"):
                continue
            findings.append(
                make_finding(
                    analyzer_id=ANALYZER_ID,
                    category="derived_freshness",
                    severity="INFO",
                    confidence=0.35,
                    file_path=watch,
                    evidence=[
                        "Potential freshness coupling detected with missing derived audit artifact.",
                        "Expected artifact candidate: {}".format(manifest),
                    ],
                    suggested_classification="TODO-BLOCKED",
                    recommended_action="ADD_RULE",
                    related_invariants=["INV-DERIVED-ARTIFACT-FRESHNESS"],
                    related_paths=[watch, manifest],
                )
            )
            if len(findings) >= 180:
                break
        if len(findings) >= 180:
            break

    return sorted(findings, key=lambda item: (item.location.file, item.severity, item.confidence))

