#ifndef DOMINO_VERSION_H
#define DOMINO_VERSION_H

#define DOMINO_VERSION_MAJOR 0
#define DOMINO_VERSION_MINOR 1
#define DOMINO_VERSION_PATCH 0

#define DOMINO_VERSION_STRING "0.1.0"

#endif /* DOMINO_VERSION_H */
