/*
AUTO-GENERATED by tool_ui_bind. DO NOT EDIT.
*/
#ifndef DOMINIUM_APPCORE_UI_ACCESSIBILITY_MAP_H
#define DOMINIUM_APPCORE_UI_ACCESSIBILITY_MAP_H

#include "domino/core/types.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dom_ui_accessibility_entry {
    const char* ui_element_id;
    const char* name;
    const char* role;
    const char* description;
    const char* localization_key;
} dom_ui_accessibility_entry;

const dom_ui_accessibility_entry* appcore_ui_accessibility_entries(u32* out_count);
const dom_ui_accessibility_entry* appcore_ui_accessibility_find(const char* ui_element_id);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DOMINIUM_APPCORE_UI_ACCESSIBILITY_MAP_H */
