/*
AUTO-GENERATED by tool_ui_bind. DO NOT EDIT.
*/
#ifndef DOMINIUM_APPCORE_UI_COMMAND_BINDING_TABLE_H
#define DOMINIUM_APPCORE_UI_COMMAND_BINDING_TABLE_H

#include "command/command_registry.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dom_ui_command_binding {
    const char* ui_element_id;
    const char* event_name;
    const char* action_key;
    u32 command_id;
} dom_ui_command_binding;

const dom_ui_command_binding* appcore_ui_command_bindings(u32* out_count);
const dom_ui_command_binding* appcore_ui_command_find_action(const char* action_key);
const dom_ui_command_binding* appcore_ui_command_find_element_event(const char* ui_element_id,
                                                                    const char* event_name);
const dom_app_command_desc* appcore_ui_command_desc_for_action(const char* action_key);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DOMINIUM_APPCORE_UI_COMMAND_BINDING_TABLE_H */
