"""LOGIC-7 debug exports."""

from src.logic.debug.compute_hooks import (
    LOGIC_DEBUG_COMPUTE_OWNER_KIND,
    build_logic_debug_compute_owner_id,
    request_logic_debug_compute,
)
from src.logic.debug.debug_engine import (
    PROCESS_LOGIC_PROBE,
    PROCESS_LOGIC_TRACE_END,
    PROCESS_LOGIC_TRACE_START,
    PROCESS_LOGIC_TRACE_TICK,
    REFUSAL_LOGIC_DEBUG_ACCESS_DENIED,
    REFUSAL_LOGIC_DEBUG_INVALID_REQUEST,
    REFUSAL_LOGIC_DEBUG_PROTOCOL_UNAVAILABLE,
    REFUSAL_LOGIC_DEBUG_REQUIRES_EXPAND,
    REFUSAL_LOGIC_DEBUG_SAMPLING_POLICY_UNREGISTERED,
    REFUSAL_LOGIC_DEBUG_SUBJECT_NOT_FOUND,
    REFUSAL_LOGIC_DEBUG_TRACE_BOUNDS_EXCEEDED,
    REFUSAL_LOGIC_DEBUG_TRACE_SESSION_NOT_FOUND,
    process_logic_probe,
    process_logic_trace_end,
    process_logic_trace_start,
    process_logic_trace_tick,
)
from src.logic.debug.runtime_state import (
    build_logic_debug_probe_request_row,
    build_logic_debug_trace_artifact_row,
    build_logic_debug_trace_request_row,
    build_logic_debug_trace_session_row,
    normalize_logic_debug_probe_request_rows,
    normalize_logic_debug_state,
    normalize_logic_debug_trace_artifact_rows,
    normalize_logic_debug_trace_request_rows,
    normalize_logic_debug_trace_session_rows,
)

__all__ = [
    "LOGIC_DEBUG_COMPUTE_OWNER_KIND",
    "PROCESS_LOGIC_PROBE",
    "PROCESS_LOGIC_TRACE_END",
    "PROCESS_LOGIC_TRACE_START",
    "PROCESS_LOGIC_TRACE_TICK",
    "REFUSAL_LOGIC_DEBUG_ACCESS_DENIED",
    "REFUSAL_LOGIC_DEBUG_INVALID_REQUEST",
    "REFUSAL_LOGIC_DEBUG_PROTOCOL_UNAVAILABLE",
    "REFUSAL_LOGIC_DEBUG_REQUIRES_EXPAND",
    "REFUSAL_LOGIC_DEBUG_SAMPLING_POLICY_UNREGISTERED",
    "REFUSAL_LOGIC_DEBUG_SUBJECT_NOT_FOUND",
    "REFUSAL_LOGIC_DEBUG_TRACE_BOUNDS_EXCEEDED",
    "REFUSAL_LOGIC_DEBUG_TRACE_SESSION_NOT_FOUND",
    "build_logic_debug_compute_owner_id",
    "build_logic_debug_probe_request_row",
    "build_logic_debug_trace_artifact_row",
    "build_logic_debug_trace_request_row",
    "build_logic_debug_trace_session_row",
    "normalize_logic_debug_probe_request_rows",
    "normalize_logic_debug_state",
    "normalize_logic_debug_trace_artifact_rows",
    "normalize_logic_debug_trace_request_rows",
    "normalize_logic_debug_trace_session_rows",
    "process_logic_probe",
    "process_logic_trace_end",
    "process_logic_trace_start",
    "process_logic_trace_tick",
    "request_logic_debug_compute",
]
