/*
AUTO-GENERATED by tool_ui_bind. DO NOT EDIT.
*/
#include "ui_bind/ui_command_binding_table.h"
#include <string.h>

static const dom_ui_command_binding k_ui_bindings[] = {
    { "launcher_ui#instances_delete", "on_click", "launcher.instances.delete_selected", 106 },
    { "launcher_ui#instances_edit", "on_click", "launcher.instances.edit_selected", 105 },
    { "launcher_ui#instances_list", "on_change", "launcher.instances.select", 103 },
    { "launcher_ui#instances_play", "on_click", "launcher.instances.play_selected", 104 },
    { "launcher_ui#nav_instances", "on_click", "launcher.nav.instances", 100 },
    { "launcher_ui#nav_mods", "on_click", "launcher.nav.mods", 102 },
    { "launcher_ui#nav_play", "on_click", "launcher.nav.play", 99 },
    { "launcher_ui#nav_settings", "on_click", "launcher.nav.settings", 101 },
    { "launcher_ui#settings_apply", "on_click", "launcher.settings.apply", 107 },
    { "setup_ui#btn_back", "on_click", "setup.nav.back", 110 },
    { "setup_ui#btn_cancel", "on_click", "setup.nav.cancel", 114 },
    { "setup_ui#btn_finish", "on_click", "setup.nav.finish", 113 },
    { "setup_ui#btn_install", "on_click", "setup.nav.install", 112 },
    { "setup_ui#btn_next", "on_click", "setup.nav.next", 111 },
    { "setup_ui#components_core_assets", "on_change", "setup.options.changed", 109 },
    { "setup_ui#components_core_game", "on_change", "setup.options.changed", 109 },
    { "setup_ui#components_list", "on_change", "setup.options.changed", 109 },
    { "setup_ui#components_opt_examples", "on_change", "setup.options.changed", 109 },
    { "setup_ui#components_opt_mods", "on_change", "setup.options.changed", 109 },
    { "setup_ui#finish_launch", "on_change", "setup.options.changed", 109 },
    { "setup_ui#path_browse", "on_click", "setup.browse_path", 108 },
    { "tool_editor#btn_add", "on_click", "tool_editor.add_widget", 121 },
    { "tool_editor#btn_delete", "on_click", "tool_editor.delete_widget", 122 },
    { "tool_editor#btn_new", "on_click", "tool_editor.new", 116 },
    { "tool_editor#btn_open", "on_click", "tool_editor.open", 117 },
    { "tool_editor#btn_save", "on_click", "tool_editor.save", 118 },
    { "tool_editor#btn_save_as", "on_click", "tool_editor.save_as", 119 },
    { "tool_editor#btn_validate", "on_click", "tool_editor.validate", 120 },
    { "tool_editor#doc_tabs", "on_tab_change", "tool_editor.tab_change", 115 },
    { "tool_editor#edit_h", "on_change", "tool_editor.prop_h", 128 },
    { "tool_editor#edit_name", "on_change", "tool_editor.prop_name", 124 },
    { "tool_editor#edit_w", "on_change", "tool_editor.prop_w", 127 },
    { "tool_editor#edit_x", "on_change", "tool_editor.prop_x", 125 },
    { "tool_editor#edit_y", "on_change", "tool_editor.prop_y", 126 },
    { "tool_editor#list_hierarchy", "on_change", "tool_editor.hierarchy_select", 123 }
};

const dom_ui_command_binding* appcore_ui_command_bindings(u32* out_count)
{
    if (out_count) {
        *out_count = (u32)(sizeof(k_ui_bindings) / sizeof(k_ui_bindings[0]));
    }
    return k_ui_bindings;
}

const dom_ui_command_binding* appcore_ui_command_find_action(const char* action_key)
{
    u32 count = 0u;
    u32 i;
    const dom_ui_command_binding* bindings = appcore_ui_command_bindings(&count);
    if (!action_key) {
        return 0;
    }
    for (i = 0u; i < count; ++i) {
        if (bindings[i].action_key && strcmp(bindings[i].action_key, action_key) == 0) {
            return &bindings[i];
        }
    }
    return 0;
}

const dom_ui_command_binding* appcore_ui_command_find_element_event(const char* ui_element_id,
                                                                    const char* event_name)
{
    u32 count = 0u;
    u32 i;
    const dom_ui_command_binding* bindings = appcore_ui_command_bindings(&count);
    if (!ui_element_id || !event_name) {
        return 0;
    }
    for (i = 0u; i < count; ++i) {
        if (bindings[i].ui_element_id && bindings[i].event_name &&
            strcmp(bindings[i].ui_element_id, ui_element_id) == 0 &&
            strcmp(bindings[i].event_name, event_name) == 0) {
            return &bindings[i];
        }
    }
    return 0;
}

const dom_app_command_desc* appcore_ui_command_desc_for_action(const char* action_key)
{
    const dom_ui_command_binding* binding = appcore_ui_command_find_action(action_key);
    if (!binding) {
        return 0;
    }
    return appcore_command_find(binding->action_key);
}
