"""Materials deterministic helpers."""

from .dimension_engine import (
    DEFAULT_FRACTIONAL_BITS,
    INT64_MAX,
    INT64_MIN,
    REFUSAL_DIMENSION_MISMATCH,
    REFUSAL_NUMERIC_OVERFLOW,
    REFUSAL_UNIT_INVALID_CONVERSION,
    DimensionError,
    FixedPointConfig,
    FixedPointOverflow,
    dimension_add,
    dimension_div,
    dimension_equals,
    dimension_mul,
    fixed_point_add,
    fixed_point_config_from_policy,
    fixed_point_div,
    fixed_point_mul,
    fixed_point_type,
    quantity_add,
    quantity_convert,
)

__all__ = [
    "DEFAULT_FRACTIONAL_BITS",
    "INT64_MAX",
    "INT64_MIN",
    "REFUSAL_DIMENSION_MISMATCH",
    "REFUSAL_NUMERIC_OVERFLOW",
    "REFUSAL_UNIT_INVALID_CONVERSION",
    "DimensionError",
    "FixedPointConfig",
    "FixedPointOverflow",
    "dimension_add",
    "dimension_div",
    "dimension_equals",
    "dimension_mul",
    "fixed_point_add",
    "fixed_point_config_from_policy",
    "fixed_point_div",
    "fixed_point_mul",
    "fixed_point_type",
    "quantity_add",
    "quantity_convert",
]
