/*
AUTO-GENERATED by tool_ui_bind. DO NOT EDIT.
*/
#include "ui_bind/ui_accessibility_map.h"
#include <string.h>

static const dom_ui_accessibility_entry k_ui_accessibility[] = {
    { "launcher_ui#instances_delete", "Delete Selected", "button", "Delete Selected", "ui.launcher_ui.instances_delete" },
    { "launcher_ui#instances_edit", "Edit Selected", "button", "Edit Selected", "ui.launcher_ui.instances_edit" },
    { "launcher_ui#instances_list", "instances_list", "list", "instances_list", "ui.launcher_ui.instances_list" },
    { "launcher_ui#instances_play", "Play Selected", "button", "Play Selected", "ui.launcher_ui.instances_play" },
    { "launcher_ui#nav_accounts", "Accounts", "button", "Accounts", "ui.launcher_ui.nav_accounts" },
    { "launcher_ui#nav_help", "Help", "button", "Help", "ui.launcher_ui.nav_help" },
    { "launcher_ui#nav_instances", "Instances", "button", "Instances", "ui.launcher_ui.nav_instances" },
    { "launcher_ui#nav_logs", "Logs", "button", "Logs", "ui.launcher_ui.nav_logs" },
    { "launcher_ui#nav_mods", "Mods", "button", "Mods", "ui.launcher_ui.nav_mods" },
    { "launcher_ui#nav_play", "Play", "button", "Play", "ui.launcher_ui.nav_play" },
    { "launcher_ui#nav_settings", "Settings", "button", "Settings", "ui.launcher_ui.nav_settings" },
    { "launcher_ui#primary_tabs", "primary_tabs", "tablist", "primary_tabs", "ui.launcher_ui.primary_tabs" },
    { "launcher_ui#settings_apply", "Apply Settings", "button", "Apply Settings", "ui.launcher_ui.settings_apply" },
    { "launcher_ui#settings_auto_update", "Auto-update launcher", "checkbox", "Auto-update launcher", "ui.launcher_ui.settings_auto_update" },
    { "launcher_ui#settings_channel", "settings_channel", "combobox", "settings_channel", "ui.launcher_ui.settings_channel" },
    { "launcher_ui#settings_install_path", "settings_install_path", "textbox", "settings_install_path", "ui.launcher_ui.settings_install_path" },
    { "launcher_ui#settings_mem_limit", "settings_mem_limit", "textbox", "settings_mem_limit", "ui.launcher_ui.settings_mem_limit" },
    { "launcher_ui#settings_renderer", "settings_renderer", "combobox", "settings_renderer", "ui.launcher_ui.settings_renderer" },
    { "launcher_ui#tab_home", "Home", "tabpanel", "Home", "ui.launcher_ui.tab_home" },
    { "launcher_ui#tab_instances", "Instances", "tabpanel", "Instances", "ui.launcher_ui.tab_instances" },
    { "launcher_ui#tab_settings", "Settings", "tabpanel", "Settings", "ui.launcher_ui.tab_settings" },
    { "setup_ui#body_tabs", "body_tabs", "tablist", "body_tabs", "ui.setup_ui.body_tabs" },
    { "setup_ui#btn_back", "Back", "button", "Back", "ui.setup_ui.btn_back" },
    { "setup_ui#btn_cancel", "Cancel", "button", "Cancel", "ui.setup_ui.btn_cancel" },
    { "setup_ui#btn_finish", "Finish", "button", "Finish", "ui.setup_ui.btn_finish" },
    { "setup_ui#btn_install", "Install", "button", "Install", "ui.setup_ui.btn_install" },
    { "setup_ui#btn_next", "Next", "button", "Next", "ui.setup_ui.btn_next" },
    { "setup_ui#components_core_assets", "Starter assets", "checkbox", "Starter assets", "ui.setup_ui.components_core_assets" },
    { "setup_ui#components_core_game", "Game files", "checkbox", "Game files", "ui.setup_ui.components_core_game" },
    { "setup_ui#components_list", "components_list", "list", "components_list", "ui.setup_ui.components_list" },
    { "setup_ui#components_opt_examples", "Example content", "checkbox", "Example content", "ui.setup_ui.components_opt_examples" },
    { "setup_ui#components_opt_mods", "Sample mods (optional)", "checkbox", "Sample mods (optional)", "ui.setup_ui.components_opt_mods" },
    { "setup_ui#finish_launch", "Launch after install", "checkbox", "Launch after install", "ui.setup_ui.finish_launch" },
    { "setup_ui#page_components", "Components", "tabpanel", "Components", "ui.setup_ui.page_components" },
    { "setup_ui#page_finish", "Finish", "tabpanel", "Finish", "ui.setup_ui.page_finish" },
    { "setup_ui#page_path", "Install Location", "tabpanel", "Install Location", "ui.setup_ui.page_path" },
    { "setup_ui#page_progress", "Progress", "tabpanel", "Progress", "ui.setup_ui.page_progress" },
    { "setup_ui#page_welcome", "Welcome", "tabpanel", "Welcome", "ui.setup_ui.page_welcome" },
    { "setup_ui#path_browse", "Browse...", "button", "Browse...", "ui.setup_ui.path_browse" },
    { "setup_ui#path_edit", "path_edit", "textbox", "path_edit", "ui.setup_ui.path_edit" },
    { "setup_ui#progress_log", "progress_log", "list", "progress_log", "ui.setup_ui.progress_log" },
    { "tool_editor#btn_add", "Add", "button", "Add", "ui.tool_editor.btn_add" },
    { "tool_editor#btn_delete", "Delete", "button", "Delete", "ui.tool_editor.btn_delete" },
    { "tool_editor#btn_new", "New", "button", "New", "ui.tool_editor.btn_new" },
    { "tool_editor#btn_open", "Open", "button", "Open", "ui.tool_editor.btn_open" },
    { "tool_editor#btn_save", "Save", "button", "Save", "ui.tool_editor.btn_save" },
    { "tool_editor#btn_save_as", "Save As", "button", "Save As", "ui.tool_editor.btn_save_as" },
    { "tool_editor#btn_validate", "Validate", "button", "Validate", "ui.tool_editor.btn_validate" },
    { "tool_editor#doc_tab_0", "Doc 1", "tabpanel", "Doc 1", "ui.tool_editor.doc_tab_0" },
    { "tool_editor#doc_tab_1", "Doc 2", "tabpanel", "Doc 2", "ui.tool_editor.doc_tab_1" },
    { "tool_editor#doc_tab_2", "Doc 3", "tabpanel", "Doc 3", "ui.tool_editor.doc_tab_2" },
    { "tool_editor#doc_tab_3", "Doc 4", "tabpanel", "Doc 4", "ui.tool_editor.doc_tab_3" },
    { "tool_editor#doc_tabs", "doc_tabs", "tablist", "doc_tabs", "ui.tool_editor.doc_tabs" },
    { "tool_editor#edit_h", "edit_h", "textbox", "edit_h", "ui.tool_editor.edit_h" },
    { "tool_editor#edit_name", "edit_name", "textbox", "edit_name", "ui.tool_editor.edit_name" },
    { "tool_editor#edit_w", "edit_w", "textbox", "edit_w", "ui.tool_editor.edit_w" },
    { "tool_editor#edit_x", "edit_x", "textbox", "edit_x", "ui.tool_editor.edit_x" },
    { "tool_editor#edit_y", "edit_y", "textbox", "edit_y", "ui.tool_editor.edit_y" },
    { "tool_editor#list_hierarchy", "list_hierarchy", "listbox", "list_hierarchy", "ui.tool_editor.list_hierarchy" },
    { "tool_editor#log_list", "log_list", "listbox", "log_list", "ui.tool_editor.log_list" },
    { "ui_doc_template_basic#button_ok", "OK", "button", "OK", "ui.ui_doc_template_basic.button_ok" }
};

const dom_ui_accessibility_entry* appcore_ui_accessibility_entries(u32* out_count)
{
    if (out_count) {
        *out_count = (u32)(sizeof(k_ui_accessibility) / sizeof(k_ui_accessibility[0]));
    }
    return k_ui_accessibility;
}

const dom_ui_accessibility_entry* appcore_ui_accessibility_find(const char* ui_element_id)
{
    u32 count = 0u;
    u32 i;
    const dom_ui_accessibility_entry* entries = appcore_ui_accessibility_entries(&count);
    if (!ui_element_id) {
        return 0;
    }
    for (i = 0u; i < count; ++i) {
        if (entries[i].ui_element_id && strcmp(entries[i].ui_element_id, ui_element_id) == 0) {
            return &entries[i];
        }
    }
    return 0;
}
