"""Deterministic EARTH-10 material/surface/albedo proxy helpers."""

from .material_proxy_engine import (
    EARTH_MATERIAL_PROXY_DEFAULT_MAX_TILES_PER_UPDATE,
    EARTH_MATERIAL_PROXY_ENGINE_VERSION,
    MATERIAL_PROXY_REGISTRY_REL,
    SURFACE_FLAG_REGISTRY_REL,
    build_earth_material_proxy_update_plan,
    build_material_proxy_field_updates,
    evaluate_earth_tile_material_proxy,
    material_proxy_albedo_permille,
    material_proxy_friction_permille,
    material_proxy_id_from_value,
    material_proxy_registry_hash,
    material_proxy_rows,
    material_proxy_value_from_id,
    material_proxy_window_hash,
    surface_flag_ids_from_mask,
    surface_flag_map_from_mask,
    surface_flag_mask_from_ids,
    surface_flag_registry_hash,
    surface_flag_rows,
)

__all__ = [
    "EARTH_MATERIAL_PROXY_DEFAULT_MAX_TILES_PER_UPDATE",
    "EARTH_MATERIAL_PROXY_ENGINE_VERSION",
    "MATERIAL_PROXY_REGISTRY_REL",
    "SURFACE_FLAG_REGISTRY_REL",
    "build_earth_material_proxy_update_plan",
    "build_material_proxy_field_updates",
    "evaluate_earth_tile_material_proxy",
    "material_proxy_albedo_permille",
    "material_proxy_friction_permille",
    "material_proxy_id_from_value",
    "material_proxy_registry_hash",
    "material_proxy_rows",
    "material_proxy_value_from_id",
    "material_proxy_window_hash",
    "surface_flag_ids_from_mask",
    "surface_flag_map_from_mask",
    "surface_flag_mask_from_ids",
    "surface_flag_registry_hash",
    "surface_flag_rows",
]
