"""Deterministic EARTH-series worldgen helpers."""

from .earth_surface_generator import EARTH_SURFACE_GENERATOR_VERSION, generate_earth_surface_tile_plan
from .hydrology_engine import (
    DEFAULT_HYDROLOGY_PARAMS_ID,
    HYDROLOGY_ENGINE_VERSION,
    HYDROLOGY_PARAMS_REGISTRY_REL,
    apply_hydrology_to_surface_tile_artifact,
    build_fluid_channel_guidance,
    build_poll_transport_stub,
    compute_hydrology_window,
    hydrology_params_rows,
    hydrology_window_hash,
)
from .climate_field_engine import (
    DEFAULT_EARTH_CLIMATE_PARAMS_ID,
    EARTH_CLIMATE_ENGINE_VERSION,
    EARTH_CLIMATE_PARAMS_REGISTRY_REL,
    build_climate_field_updates,
    build_earth_climate_update_plan,
    climate_bucket_id,
    climate_window_hash,
    due_bucket_ids,
    earth_climate_params_rows,
    evaluate_earth_tile_climate,
    is_earth_surface_tile,
)
from .tide_field_engine import (
    DEFAULT_TIDE_PARAMS_ID,
    EARTH_TIDE_ENGINE_VERSION,
    TIDE_PARAMS_REGISTRY_REL,
    build_earth_tide_update_plan,
    build_tide_coupling_stub,
    build_tide_field_updates,
    evaluate_earth_tile_tide,
    tide_bucket_id,
    tide_params_rows,
    tide_window_hash,
)
from .season_phase_engine import (
    EARTH_ORBIT_PHASE_SCALE,
    EARTH_SEASON_PHASE_ENGINE_VERSION,
    axial_tilt_mdeg,
    earth_orbit_phase,
    earth_orbit_phase_from_params,
    seasonal_wave_permille,
    solar_declination_mdeg,
)
from .tide_phase_engine import (
    EARTH_TIDE_PHASE_ENGINE_VERSION,
    EARTH_TIDE_PHASE_SCALE,
    lunar_phase,
    lunar_phase_from_params,
    phase_carrier_permille,
    phase_cosine_proxy_permille,
    rotation_phase,
    rotation_phase_from_params,
)

__all__ = [
    "DEFAULT_HYDROLOGY_PARAMS_ID",
    "DEFAULT_EARTH_CLIMATE_PARAMS_ID",
    "DEFAULT_TIDE_PARAMS_ID",
    "EARTH_CLIMATE_ENGINE_VERSION",
    "EARTH_CLIMATE_PARAMS_REGISTRY_REL",
    "EARTH_TIDE_ENGINE_VERSION",
    "EARTH_TIDE_PHASE_ENGINE_VERSION",
    "EARTH_TIDE_PHASE_SCALE",
    "build_climate_field_updates",
    "build_earth_climate_update_plan",
    "build_earth_tide_update_plan",
    "climate_bucket_id",
    "climate_window_hash",
    "due_bucket_ids",
    "earth_climate_params_rows",
    "evaluate_earth_tile_climate",
    "evaluate_earth_tile_tide",
    "EARTH_SURFACE_GENERATOR_VERSION",
    "EARTH_ORBIT_PHASE_SCALE",
    "EARTH_SEASON_PHASE_ENGINE_VERSION",
    "HYDROLOGY_ENGINE_VERSION",
    "HYDROLOGY_PARAMS_REGISTRY_REL",
    "axial_tilt_mdeg",
    "apply_hydrology_to_surface_tile_artifact",
    "build_fluid_channel_guidance",
    "build_poll_transport_stub",
    "compute_hydrology_window",
    "earth_orbit_phase",
    "earth_orbit_phase_from_params",
    "generate_earth_surface_tile_plan",
    "hydrology_params_rows",
    "hydrology_window_hash",
    "is_earth_surface_tile",
    "lunar_phase",
    "lunar_phase_from_params",
    "phase_carrier_permille",
    "phase_cosine_proxy_permille",
    "rotation_phase",
    "rotation_phase_from_params",
    "seasonal_wave_permille",
    "solar_declination_mdeg",
    "TIDE_PARAMS_REGISTRY_REL",
    "tide_bucket_id",
    "tide_params_rows",
    "tide_window_hash",
    "build_tide_coupling_stub",
    "build_tide_field_updates",
]
