include_guard(GLOBAL)

include(CMakeParseArguments)

set(DOM_TESTX_LABEL_TESTX "testx")
set(DOM_TESTX_LABEL_SMOKE "smoke")
set(DOM_TESTX_LABEL_PORTABILITY "portability")
set(DOM_TESTX_LABEL_BUILDMETA "buildmeta")

function(dom_register_product name target)
    if(NOT name)
        message(FATAL_ERROR "dom_register_product: name is required")
    endif()
    if(NOT TARGET ${target})
        message(FATAL_ERROR "dom_register_product: target '${target}' not found")
    endif()
    set_property(GLOBAL APPEND PROPERTY DOM_REGISTERED_PRODUCTS "${name}|${target}")
endfunction()

function(dom_register_renderer_backend name)
    if(NOT name)
        message(FATAL_ERROR "dom_register_renderer_backend: name is required")
    endif()
    cmake_parse_arguments(DOM "" "AVAILABILITY" "" ${ARGN})
    if(NOT DOM_AVAILABILITY)
        set(DOM_AVAILABILITY "available")
    endif()
    set_property(GLOBAL APPEND PROPERTY DOM_REGISTERED_RENDER_BACKENDS "${name}|${DOM_AVAILABILITY}")
endfunction()

function(dom_register_platform_backend name)
    if(NOT name)
        message(FATAL_ERROR "dom_register_platform_backend: name is required")
    endif()
    set_property(GLOBAL APPEND PROPERTY DOM_REGISTERED_PLATFORM_BACKENDS "${name}")
endfunction()

function(dom_register_product_cli_tests product version_test build_info_test smoke_test)
    if(NOT product)
        message(FATAL_ERROR "dom_register_product_cli_tests: product is required")
    endif()
    set_property(GLOBAL APPEND PROPERTY DOM_REGISTERED_PRODUCT_CLI_TESTS
        "${product}|${version_test}|${build_info_test}|${smoke_test}")
endfunction()

function(dom_register_renderer_tests backend explicit_test caps_test)
    if(NOT backend)
        message(FATAL_ERROR "dom_register_renderer_tests: backend is required")
    endif()
    set_property(GLOBAL APPEND PROPERTY DOM_REGISTERED_RENDERER_TESTS
        "${backend}|${explicit_test}|${caps_test}")
endfunction()

function(dom_append_test_labels test_name)
    get_property(_tests GLOBAL PROPERTY TESTS)
    if(NOT _tests)
        return()
    endif()
    list(FIND _tests "${test_name}" _idx)
    if(_idx EQUAL -1)
        return()
    endif()
    get_property(_labels TEST ${test_name} PROPERTY LABELS)
    if(NOT _labels)
        set(_labels "")
    endif()
    set(_merged ${_labels} ${ARGN})
    list(REMOVE_DUPLICATES _merged)
    set_tests_properties(${test_name} PROPERTIES LABELS "${_merged}")
endfunction()

function(dom_add_testx)
    cmake_parse_arguments(DOM "" "NAME;WORKING_DIRECTORY" "COMMAND;LABELS;ENVIRONMENT" ${ARGN})
    if(NOT DOM_NAME)
        message(FATAL_ERROR "dom_add_testx: NAME is required")
    endif()
    if(NOT DOM_COMMAND)
        message(FATAL_ERROR "dom_add_testx: COMMAND is required")
    endif()
    add_test(NAME ${DOM_NAME} COMMAND ${DOM_COMMAND})
    if(DOM_WORKING_DIRECTORY)
        set_tests_properties(${DOM_NAME} PROPERTIES WORKING_DIRECTORY "${DOM_WORKING_DIRECTORY}")
    endif()
    if(DOM_ENVIRONMENT)
        set_tests_properties(${DOM_NAME} PROPERTIES ENVIRONMENT "${DOM_ENVIRONMENT}")
    endif()
    if(DOM_LABELS)
        dom_append_test_labels(${DOM_NAME} ${DOM_LABELS})
    endif()
    dom_append_test_labels(${DOM_NAME} ${DOM_TESTX_LABEL_TESTX})
    set_property(GLOBAL APPEND PROPERTY DOM_REGISTERED_TESTX_TESTS "${DOM_NAME}")
endfunction()

function(dom_apply_default_test_labels)
    get_property(_tests GLOBAL PROPERTY TESTS)
    if(NOT _tests)
        return()
    endif()
    foreach(_t IN LISTS _tests)
        dom_append_test_labels(${_t} ${DOM_TESTX_LABEL_TESTX})
    endforeach()
endfunction()
